/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssignMembershipPlanRequest
 */
export interface AssignMembershipPlanRequest {
    /**
     * 
     * @type {string}
     * @memberof AssignMembershipPlanRequest
     */
    note?: string | null;
    /**
     * Class to join directly. Mutually exclusive with `productId`; one of
     * the two is required.
     * @type {string}
     * @memberof AssignMembershipPlanRequest
     */
    planId?: string | null;
    /**
     * Product being sold. Mutually exclusive with `planId`.
     * @type {string}
     * @memberof AssignMembershipPlanRequest
     */
    productId?: string | null;
    /**
     * YYYY-MM-DD (default today)
     * @type {string}
     * @memberof AssignMembershipPlanRequest
     */
    startedOn?: string | null;
}

/**
 * Check if a given object implements the AssignMembershipPlanRequest interface.
 */
export function instanceOfAssignMembershipPlanRequest(value: object): value is AssignMembershipPlanRequest {
    return true;
}

export function AssignMembershipPlanRequestFromJSON(json: any): AssignMembershipPlanRequest {
    return AssignMembershipPlanRequestFromJSONTyped(json, false);
}

export function AssignMembershipPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignMembershipPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'planId': json['planId'] == null ? undefined : json['planId'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'startedOn': json['startedOn'] == null ? undefined : json['startedOn'],
    };
}

export function AssignMembershipPlanRequestToJSON(json: any): AssignMembershipPlanRequest {
    return AssignMembershipPlanRequestToJSONTyped(json, false);
}

export function AssignMembershipPlanRequestToJSONTyped(value?: AssignMembershipPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'planId': value['planId'],
        'productId': value['productId'],
        'startedOn': value['startedOn'],
    };
}

