/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutoAssignSkippedItem
 */
export interface AutoAssignSkippedItem {
    /**
     * 
     * @type {string}
     * @memberof AutoAssignSkippedItem
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof AutoAssignSkippedItem
     */
    reservationId: string;
}

/**
 * Check if a given object implements the AutoAssignSkippedItem interface.
 */
export function instanceOfAutoAssignSkippedItem(value: object): value is AutoAssignSkippedItem {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    return true;
}

export function AutoAssignSkippedItemFromJSON(json: any): AutoAssignSkippedItem {
    return AutoAssignSkippedItemFromJSONTyped(json, false);
}

export function AutoAssignSkippedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoAssignSkippedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'reservationId': json['reservationId'],
    };
}

export function AutoAssignSkippedItemToJSON(json: any): AutoAssignSkippedItem {
    return AutoAssignSkippedItemToJSONTyped(json, false);
}

export function AutoAssignSkippedItemToJSONTyped(value?: AutoAssignSkippedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'reservationId': value['reservationId'],
    };
}

