/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpenseExternalRef } from './ExpenseExternalRef';
import {
    ExpenseExternalRefFromJSON,
    ExpenseExternalRefFromJSONTyped,
    ExpenseExternalRefToJSON,
    ExpenseExternalRefToJSONTyped,
} from './ExpenseExternalRef';
import type { ExpenseAttachment } from './ExpenseAttachment';
import {
    ExpenseAttachmentFromJSON,
    ExpenseAttachmentFromJSONTyped,
    ExpenseAttachmentToJSON,
    ExpenseAttachmentToJSONTyped,
} from './ExpenseAttachment';

/**
 * 
 * @export
 * @interface CreateExpenseRequest
 */
export interface CreateExpenseRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateExpenseRequest
     */
    amount: number;
    /**
     * 
     * @type {Array<ExpenseAttachment>}
     * @memberof CreateExpenseRequest
     */
    attachments?: Array<ExpenseAttachment> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseRequest
     */
    categoryId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseRequest
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseRequest
     */
    expenseDate: string;
    /**
     * 
     * @type {Array<ExpenseExternalRef>}
     * @memberof CreateExpenseRequest
     */
    externalRefs?: Array<ExpenseExternalRef> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseRequest
     */
    memo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseRequest
     */
    payee: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseRequest
     */
    status?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateExpenseRequest
     */
    taxAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseRequest
     */
    taxCategory?: string | null;
}

/**
 * Check if a given object implements the CreateExpenseRequest interface.
 */
export function instanceOfCreateExpenseRequest(value: object): value is CreateExpenseRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('expenseDate' in value) || value['expenseDate'] === undefined) return false;
    if (!('payee' in value) || value['payee'] === undefined) return false;
    return true;
}

export function CreateExpenseRequestFromJSON(json: any): CreateExpenseRequest {
    return CreateExpenseRequestFromJSONTyped(json, false);
}

export function CreateExpenseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExpenseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(ExpenseAttachmentFromJSON)),
        'categoryId': json['categoryId'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'expenseDate': json['expenseDate'],
        'externalRefs': json['externalRefs'] == null ? undefined : ((json['externalRefs'] as Array<any>).map(ExpenseExternalRefFromJSON)),
        'memo': json['memo'] == null ? undefined : json['memo'],
        'payee': json['payee'],
        'status': json['status'] == null ? undefined : json['status'],
        'taxAmount': json['taxAmount'] == null ? undefined : json['taxAmount'],
        'taxCategory': json['taxCategory'] == null ? undefined : json['taxCategory'],
    };
}

export function CreateExpenseRequestToJSON(json: any): CreateExpenseRequest {
    return CreateExpenseRequestToJSONTyped(json, false);
}

export function CreateExpenseRequestToJSONTyped(value?: CreateExpenseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(ExpenseAttachmentToJSON)),
        'categoryId': value['categoryId'],
        'currency': value['currency'],
        'expenseDate': value['expenseDate'],
        'externalRefs': value['externalRefs'] == null ? undefined : ((value['externalRefs'] as Array<any>).map(ExpenseExternalRefToJSON)),
        'memo': value['memo'],
        'payee': value['payee'],
        'status': value['status'],
        'taxAmount': value['taxAmount'],
        'taxCategory': value['taxCategory'],
    };
}

