/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateQuotationItemRequest } from './CreateQuotationItemRequest';
import {
    CreateQuotationItemRequestFromJSON,
    CreateQuotationItemRequestFromJSONTyped,
    CreateQuotationItemRequestToJSON,
    CreateQuotationItemRequestToJSONTyped,
} from './CreateQuotationItemRequest';

/**
 * 
 * @export
 * @interface CreateQuotationRequest
 */
export interface CreateQuotationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    clientEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    clientName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateQuotationRequest
     */
    createPaymentLink?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    currency?: string | null;
    /**
     * 
     * @type {Array<CreateQuotationItemRequest>}
     * @memberof CreateQuotationRequest
     */
    items: Array<CreateQuotationItemRequest>;
    /**
     * 
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    quotationNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateQuotationRequest
     */
    sendEmail?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    status?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateQuotationRequest
     */
    taxAmount?: number | null;
    /**
     * Omitted by clients that let the server pick the default validity
     * (30 days from today), so operators cannot skew it via device clock.
     * @type {string}
     * @memberof CreateQuotationRequest
     */
    validUntil?: string | null;
}

/**
 * Check if a given object implements the CreateQuotationRequest interface.
 */
export function instanceOfCreateQuotationRequest(value: object): value is CreateQuotationRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CreateQuotationRequestFromJSON(json: any): CreateQuotationRequest {
    return CreateQuotationRequestFromJSONTyped(json, false);
}

export function CreateQuotationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateQuotationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientEmail': json['clientEmail'] == null ? undefined : json['clientEmail'],
        'clientId': json['clientId'],
        'clientName': json['clientName'] == null ? undefined : json['clientName'],
        'createPaymentLink': json['createPaymentLink'] == null ? undefined : json['createPaymentLink'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'items': ((json['items'] as Array<any>).map(CreateQuotationItemRequestFromJSON)),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'quotationNumber': json['quotationNumber'] == null ? undefined : json['quotationNumber'],
        'sendEmail': json['sendEmail'] == null ? undefined : json['sendEmail'],
        'status': json['status'] == null ? undefined : json['status'],
        'taxAmount': json['taxAmount'] == null ? undefined : json['taxAmount'],
        'validUntil': json['validUntil'] == null ? undefined : json['validUntil'],
    };
}

export function CreateQuotationRequestToJSON(json: any): CreateQuotationRequest {
    return CreateQuotationRequestToJSONTyped(json, false);
}

export function CreateQuotationRequestToJSONTyped(value?: CreateQuotationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientEmail': value['clientEmail'],
        'clientId': value['clientId'],
        'clientName': value['clientName'],
        'createPaymentLink': value['createPaymentLink'],
        'currency': value['currency'],
        'items': ((value['items'] as Array<any>).map(CreateQuotationItemRequestToJSON)),
        'notes': value['notes'],
        'quotationNumber': value['quotationNumber'],
        'sendEmail': value['sendEmail'],
        'status': value['status'],
        'taxAmount': value['taxAmount'],
        'validUntil': value['validUntil'],
    };
}

