/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderProductOptionGroupRequest } from './OrderProductOptionGroupRequest';
import {
    OrderProductOptionGroupRequestFromJSON,
    OrderProductOptionGroupRequestFromJSONTyped,
    OrderProductOptionGroupRequestToJSON,
    OrderProductOptionGroupRequestToJSONTyped,
} from './OrderProductOptionGroupRequest';
import type { OrderProductVariationRequest } from './OrderProductVariationRequest';
import {
    OrderProductVariationRequestFromJSON,
    OrderProductVariationRequestFromJSONTyped,
    OrderProductVariationRequestToJSON,
    OrderProductVariationRequestToJSONTyped,
} from './OrderProductVariationRequest';

/**
 * 
 * @export
 * @interface CreateOrderProductRequest
 */
export interface CreateOrderProductRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    billingCycle: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    category?: string | null;
    /**
     * Storefront category (`cat_…`, from `GET /v1/storekit/categories`).
     * 
     * Distinct from `category`, which is the ERP-side free-text classification
     * and has no storefront meaning.
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    id?: string | null;
    /**
     * Optional client-supplied key to make creation idempotent across retries.
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    idempotencyKey?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrderProductRequest
     */
    imageStorageKeys?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    janCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    kind: string;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderProductRequest
     */
    listPrice: number;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    name: string;
    /**
     * 選択肢 (トッピング等)。省略は「選択肢の話をしていない」。
     * @type {Array<OrderProductOptionGroupRequest>}
     * @memberof CreateOrderProductRequest
     */
    optionGroups?: Array<OrderProductOptionGroupRequest> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    publicationDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    publicationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    publicationStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    skuCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    subcategory?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrderProductRequest
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderProductRequest
     */
    upcCode?: string | null;
    /**
     * 
     * @type {Array<OrderProductVariationRequest>}
     * @memberof CreateOrderProductRequest
     */
    variations?: Array<OrderProductVariationRequest> | null;
}

/**
 * Check if a given object implements the CreateOrderProductRequest interface.
 */
export function instanceOfCreateOrderProductRequest(value: object): value is CreateOrderProductRequest {
    if (!('billingCycle' in value) || value['billingCycle'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('listPrice' in value) || value['listPrice'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateOrderProductRequestFromJSON(json: any): CreateOrderProductRequest {
    return CreateOrderProductRequestFromJSONTyped(json, false);
}

export function CreateOrderProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'billingCycle': json['billingCycle'],
        'category': json['category'] == null ? undefined : json['category'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
        'imageStorageKeys': json['imageStorageKeys'] == null ? undefined : json['imageStorageKeys'],
        'janCode': json['janCode'] == null ? undefined : json['janCode'],
        'kind': json['kind'],
        'listPrice': json['listPrice'],
        'name': json['name'],
        'optionGroups': json['optionGroups'] == null ? undefined : ((json['optionGroups'] as Array<any>).map(OrderProductOptionGroupRequestFromJSON)),
        'publicationDescription': json['publicationDescription'] == null ? undefined : json['publicationDescription'],
        'publicationName': json['publicationName'] == null ? undefined : json['publicationName'],
        'publicationStatus': json['publicationStatus'] == null ? undefined : json['publicationStatus'],
        'skuCode': json['skuCode'] == null ? undefined : json['skuCode'],
        'status': json['status'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'upcCode': json['upcCode'] == null ? undefined : json['upcCode'],
        'variations': json['variations'] == null ? undefined : ((json['variations'] as Array<any>).map(OrderProductVariationRequestFromJSON)),
    };
}

export function CreateOrderProductRequestToJSON(json: any): CreateOrderProductRequest {
    return CreateOrderProductRequestToJSONTyped(json, false);
}

export function CreateOrderProductRequestToJSONTyped(value?: CreateOrderProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billingCycle': value['billingCycle'],
        'category': value['category'],
        'categoryId': value['categoryId'],
        'description': value['description'],
        'id': value['id'],
        'idempotencyKey': value['idempotencyKey'],
        'imageStorageKeys': value['imageStorageKeys'],
        'janCode': value['janCode'],
        'kind': value['kind'],
        'listPrice': value['listPrice'],
        'name': value['name'],
        'optionGroups': value['optionGroups'] == null ? undefined : ((value['optionGroups'] as Array<any>).map(OrderProductOptionGroupRequestToJSON)),
        'publicationDescription': value['publicationDescription'],
        'publicationName': value['publicationName'],
        'publicationStatus': value['publicationStatus'],
        'skuCode': value['skuCode'],
        'status': value['status'],
        'subcategory': value['subcategory'],
        'tags': value['tags'],
        'upcCode': value['upcCode'],
        'variations': value['variations'] == null ? undefined : ((value['variations'] as Array<any>).map(OrderProductVariationRequestToJSON)),
    };
}

