/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatedEntityResponse
 */
export interface CreatedEntityResponse {
    /**
     * 
     * @type {string}
     * @memberof CreatedEntityResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CreatedEntityResponse interface.
 */
export function instanceOfCreatedEntityResponse(value: object): value is CreatedEntityResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreatedEntityResponseFromJSON(json: any): CreatedEntityResponse {
    return CreatedEntityResponseFromJSONTyped(json, false);
}

export function CreatedEntityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedEntityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreatedEntityResponseToJSON(json: any): CreatedEntityResponse {
    return CreatedEntityResponseToJSONTyped(json, false);
}

export function CreatedEntityResponseToJSONTyped(value?: CreatedEntityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

