/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SummaryPeriodResponse } from './SummaryPeriodResponse';
import {
    SummaryPeriodResponseFromJSON,
    SummaryPeriodResponseFromJSONTyped,
    SummaryPeriodResponseToJSON,
    SummaryPeriodResponseToJSONTyped,
} from './SummaryPeriodResponse';
import type { CurrencyTotalsResponse } from './CurrencyTotalsResponse';
import {
    CurrencyTotalsResponseFromJSON,
    CurrencyTotalsResponseFromJSONTyped,
    CurrencyTotalsResponseToJSON,
    CurrencyTotalsResponseToJSONTyped,
} from './CurrencyTotalsResponse';

/**
 * 
 * @export
 * @interface CustomerPurchaseSummaryResponse
 */
export interface CustomerPurchaseSummaryResponse {
    /**
     * キャンセル（`cancelled` / `rejected`）。金額にも回数にも入れていない。
     * @type {number}
     * @memberof CustomerPurchaseSummaryResponse
     */
    cancelledCount: number;
    /**
     * この集計がいつ時点かを表す UTC 時刻。都度計算なので常に「今」で、
     * 「確定済みだが提供日がまだ来ていない」の判定基準もこの時刻。
     * @type {string}
     * @memberof CustomerPurchaseSummaryResponse
     */
    computedAt: string;
    /**
     * 通貨ごとの金額の内訳。購入が無ければ空。
     * @type {Array<CurrencyTotalsResponse>}
     * @memberof CustomerPurchaseSummaryResponse
     */
    currencies: Array<CurrencyTotalsResponse>;
    /**
     * 
     * @type {string}
     * @memberof CustomerPurchaseSummaryResponse
     */
    customerId: string;
    /**
     * 初回購入日（Asia/Tokyo）。購入が無ければ `null`。
     * @type {string}
     * @memberof CustomerPurchaseSummaryResponse
     */
    firstPurchaseDate?: string | null;
    /**
     * 最終購入日（Asia/Tokyo）。購入が無ければ `null`。
     * @type {string}
     * @memberof CustomerPurchaseSummaryResponse
     */
    lastPurchaseDate?: string | null;
    /**
     * no-show。金額にも回数にも入れていない。
     * @type {number}
     * @memberof CustomerPurchaseSummaryResponse
     */
    noShowCount: number;
    /**
     * まだ確定していない予約（申込中・支払待ち・変更/キャンセル申請中など）。
     * @type {number}
     * @memberof CustomerPurchaseSummaryResponse
     */
    pendingCount: number;
    /**
     * 
     * @type {SummaryPeriodResponse}
     * @memberof CustomerPurchaseSummaryResponse
     */
    period: SummaryPeriodResponse;
    /**
     * 購入回数（通貨をまたいだ合計）。
     * @type {number}
     * @memberof CustomerPurchaseSummaryResponse
     */
    purchaseCount: number;
    /**
     * 購入のうち金額が未確定（0）のもの。0 を足しただけの回数が分かる。
     * @type {number}
     * @memberof CustomerPurchaseSummaryResponse
     */
    unpricedCount: number;
    /**
     * 確定済みだが提供日がまだ来ていない予約。購入には数えていない。
     * @type {number}
     * @memberof CustomerPurchaseSummaryResponse
     */
    upcomingCount: number;
}

/**
 * Check if a given object implements the CustomerPurchaseSummaryResponse interface.
 */
export function instanceOfCustomerPurchaseSummaryResponse(value: object): value is CustomerPurchaseSummaryResponse {
    if (!('cancelledCount' in value) || value['cancelledCount'] === undefined) return false;
    if (!('computedAt' in value) || value['computedAt'] === undefined) return false;
    if (!('currencies' in value) || value['currencies'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('noShowCount' in value) || value['noShowCount'] === undefined) return false;
    if (!('pendingCount' in value) || value['pendingCount'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('purchaseCount' in value) || value['purchaseCount'] === undefined) return false;
    if (!('unpricedCount' in value) || value['unpricedCount'] === undefined) return false;
    if (!('upcomingCount' in value) || value['upcomingCount'] === undefined) return false;
    return true;
}

export function CustomerPurchaseSummaryResponseFromJSON(json: any): CustomerPurchaseSummaryResponse {
    return CustomerPurchaseSummaryResponseFromJSONTyped(json, false);
}

export function CustomerPurchaseSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPurchaseSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cancelledCount': json['cancelledCount'],
        'computedAt': json['computedAt'],
        'currencies': ((json['currencies'] as Array<any>).map(CurrencyTotalsResponseFromJSON)),
        'customerId': json['customerId'],
        'firstPurchaseDate': json['firstPurchaseDate'] == null ? undefined : json['firstPurchaseDate'],
        'lastPurchaseDate': json['lastPurchaseDate'] == null ? undefined : json['lastPurchaseDate'],
        'noShowCount': json['noShowCount'],
        'pendingCount': json['pendingCount'],
        'period': SummaryPeriodResponseFromJSON(json['period']),
        'purchaseCount': json['purchaseCount'],
        'unpricedCount': json['unpricedCount'],
        'upcomingCount': json['upcomingCount'],
    };
}

export function CustomerPurchaseSummaryResponseToJSON(json: any): CustomerPurchaseSummaryResponse {
    return CustomerPurchaseSummaryResponseToJSONTyped(json, false);
}

export function CustomerPurchaseSummaryResponseToJSONTyped(value?: CustomerPurchaseSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cancelledCount': value['cancelledCount'],
        'computedAt': value['computedAt'],
        'currencies': ((value['currencies'] as Array<any>).map(CurrencyTotalsResponseToJSON)),
        'customerId': value['customerId'],
        'firstPurchaseDate': value['firstPurchaseDate'],
        'lastPurchaseDate': value['lastPurchaseDate'],
        'noShowCount': value['noShowCount'],
        'pendingCount': value['pendingCount'],
        'period': SummaryPeriodResponseToJSON(value['period']),
        'purchaseCount': value['purchaseCount'],
        'unpricedCount': value['unpricedCount'],
        'upcomingCount': value['upcomingCount'],
    };
}

