/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerPurchaseSummaryRowResponse
 */
export interface CustomerPurchaseSummaryRowResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    cancelledCount: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    firstPurchaseDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    lastPurchaseDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    noShowCount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    paidAmount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    pendingCount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    purchaseCount: number;
    /**
     * 累計購入額。税込。
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    totalAmount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    unpricedCount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerPurchaseSummaryRowResponse
     */
    upcomingCount: number;
}

/**
 * Check if a given object implements the CustomerPurchaseSummaryRowResponse interface.
 */
export function instanceOfCustomerPurchaseSummaryRowResponse(value: object): value is CustomerPurchaseSummaryRowResponse {
    if (!('cancelledCount' in value) || value['cancelledCount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('noShowCount' in value) || value['noShowCount'] === undefined) return false;
    if (!('paidAmount' in value) || value['paidAmount'] === undefined) return false;
    if (!('pendingCount' in value) || value['pendingCount'] === undefined) return false;
    if (!('purchaseCount' in value) || value['purchaseCount'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    if (!('unpricedCount' in value) || value['unpricedCount'] === undefined) return false;
    if (!('upcomingCount' in value) || value['upcomingCount'] === undefined) return false;
    return true;
}

export function CustomerPurchaseSummaryRowResponseFromJSON(json: any): CustomerPurchaseSummaryRowResponse {
    return CustomerPurchaseSummaryRowResponseFromJSONTyped(json, false);
}

export function CustomerPurchaseSummaryRowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPurchaseSummaryRowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cancelledCount': json['cancelledCount'],
        'currency': json['currency'],
        'customerId': json['customerId'],
        'firstPurchaseDate': json['firstPurchaseDate'] == null ? undefined : json['firstPurchaseDate'],
        'lastPurchaseDate': json['lastPurchaseDate'] == null ? undefined : json['lastPurchaseDate'],
        'noShowCount': json['noShowCount'],
        'paidAmount': json['paidAmount'],
        'pendingCount': json['pendingCount'],
        'purchaseCount': json['purchaseCount'],
        'totalAmount': json['totalAmount'],
        'unpricedCount': json['unpricedCount'],
        'upcomingCount': json['upcomingCount'],
    };
}

export function CustomerPurchaseSummaryRowResponseToJSON(json: any): CustomerPurchaseSummaryRowResponse {
    return CustomerPurchaseSummaryRowResponseToJSONTyped(json, false);
}

export function CustomerPurchaseSummaryRowResponseToJSONTyped(value?: CustomerPurchaseSummaryRowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cancelledCount': value['cancelledCount'],
        'currency': value['currency'],
        'customerId': value['customerId'],
        'firstPurchaseDate': value['firstPurchaseDate'],
        'lastPurchaseDate': value['lastPurchaseDate'],
        'noShowCount': value['noShowCount'],
        'paidAmount': value['paidAmount'],
        'pendingCount': value['pendingCount'],
        'purchaseCount': value['purchaseCount'],
        'totalAmount': value['totalAmount'],
        'unpricedCount': value['unpricedCount'],
        'upcomingCount': value['upcomingCount'],
    };
}

