/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluateFeatureFlagsRequest
 */
export interface EvaluateFeatureFlagsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof EvaluateFeatureFlagsRequest
     */
    keys: Array<string>;
}

/**
 * Check if a given object implements the EvaluateFeatureFlagsRequest interface.
 */
export function instanceOfEvaluateFeatureFlagsRequest(value: object): value is EvaluateFeatureFlagsRequest {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function EvaluateFeatureFlagsRequestFromJSON(json: any): EvaluateFeatureFlagsRequest {
    return EvaluateFeatureFlagsRequestFromJSONTyped(json, false);
}

export function EvaluateFeatureFlagsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluateFeatureFlagsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': json['keys'],
    };
}

export function EvaluateFeatureFlagsRequestToJSON(json: any): EvaluateFeatureFlagsRequest {
    return EvaluateFeatureFlagsRequestToJSONTyped(json, false);
}

export function EvaluateFeatureFlagsRequestToJSONTyped(value?: EvaluateFeatureFlagsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': value['keys'],
    };
}

