/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureFlagValue
 */
export interface FeatureFlagValue {
    /**
     * 
     * @type {boolean}
     * @memberof FeatureFlagValue
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeatureFlagValue
     */
    key: string;
}

/**
 * Check if a given object implements the FeatureFlagValue interface.
 */
export function instanceOfFeatureFlagValue(value: object): value is FeatureFlagValue {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function FeatureFlagValueFromJSON(json: any): FeatureFlagValue {
    return FeatureFlagValueFromJSONTyped(json, false);
}

export function FeatureFlagValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureFlagValue {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'key': json['key'],
    };
}

export function FeatureFlagValueToJSON(json: any): FeatureFlagValue {
    return FeatureFlagValueToJSONTyped(json, false);
}

export function FeatureFlagValueToJSONTyped(value?: FeatureFlagValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'key': value['key'],
    };
}

