/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForecastBucket
 */
export interface ForecastBucket {
    /**
     * 
     * @type {number}
     * @memberof ForecastBucket
     */
    dealCount: number;
    /**
     * 
     * @type {number}
     * @memberof ForecastBucket
     */
    grossAmount: number;
    /**
     * 
     * @type {string}
     * @memberof ForecastBucket
     */
    month?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ForecastBucket
     */
    weightedAmount: number;
}

/**
 * Check if a given object implements the ForecastBucket interface.
 */
export function instanceOfForecastBucket(value: object): value is ForecastBucket {
    if (!('dealCount' in value) || value['dealCount'] === undefined) return false;
    if (!('grossAmount' in value) || value['grossAmount'] === undefined) return false;
    if (!('weightedAmount' in value) || value['weightedAmount'] === undefined) return false;
    return true;
}

export function ForecastBucketFromJSON(json: any): ForecastBucket {
    return ForecastBucketFromJSONTyped(json, false);
}

export function ForecastBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'dealCount': json['dealCount'],
        'grossAmount': json['grossAmount'],
        'month': json['month'] == null ? undefined : json['month'],
        'weightedAmount': json['weightedAmount'],
    };
}

export function ForecastBucketToJSON(json: any): ForecastBucket {
    return ForecastBucketToJSONTyped(json, false);
}

export function ForecastBucketToJSONTyped(value?: ForecastBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dealCount': value['dealCount'],
        'grossAmount': value['grossAmount'],
        'month': value['month'],
        'weightedAmount': value['weightedAmount'],
    };
}

