/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FulfillmentMethodResponse
 */
export interface FulfillmentMethodResponse {
    /**
     * 
     * @type {string}
     * @memberof FulfillmentMethodResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentMethodResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentMethodResponse
     */
    name: string;
}

/**
 * Check if a given object implements the FulfillmentMethodResponse interface.
 */
export function instanceOfFulfillmentMethodResponse(value: object): value is FulfillmentMethodResponse {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FulfillmentMethodResponseFromJSON(json: any): FulfillmentMethodResponse {
    return FulfillmentMethodResponseFromJSONTyped(json, false);
}

export function FulfillmentMethodResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentMethodResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function FulfillmentMethodResponseToJSON(json: any): FulfillmentMethodResponse {
    return FulfillmentMethodResponseToJSONTyped(json, false);
}

export function FulfillmentMethodResponseToJSONTyped(value?: FulfillmentMethodResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
    };
}

