/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateResourceTimeSlotsRequest
 */
export interface GenerateResourceTimeSlotsRequest {
    /**
     * Run the complete lock, validation, and conflict plan without writes.
     * @type {boolean}
     * @memberof GenerateResourceTimeSlotsRequest
     */
    dryRun?: boolean;
    /**
     * Inclusive local date in each matching schedule rule's timezone.
     * @type {Date}
     * @memberof GenerateResourceTimeSlotsRequest
     */
    from: Date;
    /**
     * Inclusive local date in each matching schedule rule's timezone.
     * @type {Date}
     * @memberof GenerateResourceTimeSlotsRequest
     */
    to: Date;
}

/**
 * Check if a given object implements the GenerateResourceTimeSlotsRequest interface.
 */
export function instanceOfGenerateResourceTimeSlotsRequest(value: object): value is GenerateResourceTimeSlotsRequest {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function GenerateResourceTimeSlotsRequestFromJSON(json: any): GenerateResourceTimeSlotsRequest {
    return GenerateResourceTimeSlotsRequestFromJSONTyped(json, false);
}

export function GenerateResourceTimeSlotsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateResourceTimeSlotsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'dryRun': json['dryRun'] == null ? undefined : json['dryRun'],
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
    };
}

export function GenerateResourceTimeSlotsRequestToJSON(json: any): GenerateResourceTimeSlotsRequest {
    return GenerateResourceTimeSlotsRequestToJSONTyped(json, false);
}

export function GenerateResourceTimeSlotsRequestToJSONTyped(value?: GenerateResourceTimeSlotsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dryRun': value['dryRun'],
        'from': value['from'].toISOString().substring(0,10),
        'to': value['to'].toISOString().substring(0,10),
    };
}

