/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GolfProductSlotBody
 */
export interface GolfProductSlotBody {
    /**
     * 
     * @type {string}
     * @memberof GolfProductSlotBody
     */
    endTime: string;
    /**
     * 
     * @type {number}
     * @memberof GolfProductSlotBody
     */
    maxGroups?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GolfProductSlotBody
     */
    maxPlayers?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GolfProductSlotBody
     */
    startTime: string;
    /**
     * 
     * @type {number}
     * @memberof GolfProductSlotBody
     */
    weekday: number;
}

/**
 * Check if a given object implements the GolfProductSlotBody interface.
 */
export function instanceOfGolfProductSlotBody(value: object): value is GolfProductSlotBody {
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('weekday' in value) || value['weekday'] === undefined) return false;
    return true;
}

export function GolfProductSlotBodyFromJSON(json: any): GolfProductSlotBody {
    return GolfProductSlotBodyFromJSONTyped(json, false);
}

export function GolfProductSlotBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GolfProductSlotBody {
    if (json == null) {
        return json;
    }
    return {
        
        'endTime': json['endTime'],
        'maxGroups': json['maxGroups'] == null ? undefined : json['maxGroups'],
        'maxPlayers': json['maxPlayers'] == null ? undefined : json['maxPlayers'],
        'startTime': json['startTime'],
        'weekday': json['weekday'],
    };
}

export function GolfProductSlotBodyToJSON(json: any): GolfProductSlotBody {
    return GolfProductSlotBodyToJSONTyped(json, false);
}

export function GolfProductSlotBodyToJSONTyped(value?: GolfProductSlotBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endTime': value['endTime'],
        'maxGroups': value['maxGroups'],
        'maxPlayers': value['maxPlayers'],
        'startTime': value['startTime'],
        'weekday': value['weekday'],
    };
}

