/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GolfMonthlySettlementCancellations
 */
export interface GolfMonthlySettlementCancellations {
    /**
     * 
     * @type {number}
     * @memberof GolfMonthlySettlementCancellations
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof GolfMonthlySettlementCancellations
     */
    feeOutstandingAmount: number;
}

/**
 * Check if a given object implements the GolfMonthlySettlementCancellations interface.
 */
export function instanceOfGolfMonthlySettlementCancellations(value: object): value is GolfMonthlySettlementCancellations {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('feeOutstandingAmount' in value) || value['feeOutstandingAmount'] === undefined) return false;
    return true;
}

export function GolfMonthlySettlementCancellationsFromJSON(json: any): GolfMonthlySettlementCancellations {
    return GolfMonthlySettlementCancellationsFromJSONTyped(json, false);
}

export function GolfMonthlySettlementCancellationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GolfMonthlySettlementCancellations {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'feeOutstandingAmount': json['feeOutstandingAmount'],
    };
}

export function GolfMonthlySettlementCancellationsToJSON(json: any): GolfMonthlySettlementCancellations {
    return GolfMonthlySettlementCancellationsToJSONTyped(json, false);
}

export function GolfMonthlySettlementCancellationsToJSONTyped(value?: GolfMonthlySettlementCancellations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'feeOutstandingAmount': value['feeOutstandingAmount'],
    };
}

