/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InventoryLocationResponse } from './InventoryLocationResponse';
import {
    InventoryLocationResponseFromJSON,
    InventoryLocationResponseFromJSONTyped,
    InventoryLocationResponseToJSON,
    InventoryLocationResponseToJSONTyped,
} from './InventoryLocationResponse';

/**
 * 
 * @export
 * @interface InventoryLocationListResponse
 */
export interface InventoryLocationListResponse {
    /**
     * 
     * @type {Array<InventoryLocationResponse>}
     * @memberof InventoryLocationListResponse
     */
    items: Array<InventoryLocationResponse>;
}

/**
 * Check if a given object implements the InventoryLocationListResponse interface.
 */
export function instanceOfInventoryLocationListResponse(value: object): value is InventoryLocationListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function InventoryLocationListResponseFromJSON(json: any): InventoryLocationListResponse {
    return InventoryLocationListResponseFromJSONTyped(json, false);
}

export function InventoryLocationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryLocationListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(InventoryLocationResponseFromJSON)),
    };
}

export function InventoryLocationListResponseToJSON(json: any): InventoryLocationListResponse {
    return InventoryLocationListResponseToJSONTyped(json, false);
}

export function InventoryLocationListResponseToJSONTyped(value?: InventoryLocationListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(InventoryLocationResponseToJSON)),
    };
}

