/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceBillToResponseOneOf2
 */
export interface InvoiceBillToResponseOneOf2 {
    /**
     * 
     * @type {InvoiceBillToResponseOneOf2KindEnum}
     * @memberof InvoiceBillToResponseOneOf2
     */
    kind: InvoiceBillToResponseOneOf2KindEnum;
    /**
     * 
     * @type {string}
     * @memberof InvoiceBillToResponseOneOf2
     */
    legacyReferenceId: string;
    /**
     * 
     * @type {any}
     * @memberof InvoiceBillToResponseOneOf2
     */
    snapshot: any | null;
}


/**
 * @export
 */
export const InvoiceBillToResponseOneOf2KindEnum = {
    LegacyUnresolved: 'legacy_unresolved'
} as const;
export type InvoiceBillToResponseOneOf2KindEnum = typeof InvoiceBillToResponseOneOf2KindEnum[keyof typeof InvoiceBillToResponseOneOf2KindEnum];


/**
 * Check if a given object implements the InvoiceBillToResponseOneOf2 interface.
 */
export function instanceOfInvoiceBillToResponseOneOf2(value: object): value is InvoiceBillToResponseOneOf2 {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('legacyReferenceId' in value) || value['legacyReferenceId'] === undefined) return false;
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    return true;
}

export function InvoiceBillToResponseOneOf2FromJSON(json: any): InvoiceBillToResponseOneOf2 {
    return InvoiceBillToResponseOneOf2FromJSONTyped(json, false);
}

export function InvoiceBillToResponseOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceBillToResponseOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'legacyReferenceId': json['legacyReferenceId'],
        'snapshot': json['snapshot'],
    };
}

export function InvoiceBillToResponseOneOf2ToJSON(json: any): InvoiceBillToResponseOneOf2 {
    return InvoiceBillToResponseOneOf2ToJSONTyped(json, false);
}

export function InvoiceBillToResponseOneOf2ToJSONTyped(value?: InvoiceBillToResponseOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'legacyReferenceId': value['legacyReferenceId'],
        'snapshot': value['snapshot'],
    };
}

