/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MembershipPlanAssignmentResponse
 */
export interface MembershipPlanAssignmentResponse {
    /**
     * 
     * @type {string}
     * @memberof MembershipPlanAssignmentResponse
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipPlanAssignmentResponse
     */
    endedOn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MembershipPlanAssignmentResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipPlanAssignmentResponse
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MembershipPlanAssignmentResponse
     */
    planId: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipPlanAssignmentResponse
     */
    startedOn: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipPlanAssignmentResponse
     */
    status: string;
}

/**
 * Check if a given object implements the MembershipPlanAssignmentResponse interface.
 */
export function instanceOfMembershipPlanAssignmentResponse(value: object): value is MembershipPlanAssignmentResponse {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('startedOn' in value) || value['startedOn'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MembershipPlanAssignmentResponseFromJSON(json: any): MembershipPlanAssignmentResponse {
    return MembershipPlanAssignmentResponseFromJSONTyped(json, false);
}

export function MembershipPlanAssignmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipPlanAssignmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customerId'],
        'endedOn': json['endedOn'] == null ? undefined : json['endedOn'],
        'id': json['id'],
        'note': json['note'] == null ? undefined : json['note'],
        'planId': json['planId'],
        'startedOn': json['startedOn'],
        'status': json['status'],
    };
}

export function MembershipPlanAssignmentResponseToJSON(json: any): MembershipPlanAssignmentResponse {
    return MembershipPlanAssignmentResponseToJSONTyped(json, false);
}

export function MembershipPlanAssignmentResponseToJSONTyped(value?: MembershipPlanAssignmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customerId': value['customerId'],
        'endedOn': value['endedOn'],
        'id': value['id'],
        'note': value['note'],
        'planId': value['planId'],
        'startedOn': value['startedOn'],
        'status': value['status'],
    };
}

