/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MembershipCustomerResponse } from './MembershipCustomerResponse';
import {
    MembershipCustomerResponseFromJSON,
    MembershipCustomerResponseFromJSONTyped,
    MembershipCustomerResponseToJSON,
    MembershipCustomerResponseToJSONTyped,
} from './MembershipCustomerResponse';
import type { MembershipPlanAssignmentResponse } from './MembershipPlanAssignmentResponse';
import {
    MembershipPlanAssignmentResponseFromJSON,
    MembershipPlanAssignmentResponseFromJSONTyped,
    MembershipPlanAssignmentResponseToJSON,
    MembershipPlanAssignmentResponseToJSONTyped,
} from './MembershipPlanAssignmentResponse';
import type { CustomerConsentResponse } from './CustomerConsentResponse';
import {
    CustomerConsentResponseFromJSON,
    CustomerConsentResponseFromJSONTyped,
    CustomerConsentResponseToJSON,
    CustomerConsentResponseToJSONTyped,
} from './CustomerConsentResponse';
import type { CustomerSubjectResponse } from './CustomerSubjectResponse';
import {
    CustomerSubjectResponseFromJSON,
    CustomerSubjectResponseFromJSONTyped,
    CustomerSubjectResponseToJSON,
    CustomerSubjectResponseToJSONTyped,
} from './CustomerSubjectResponse';
import type { MembershipPlanResponse } from './MembershipPlanResponse';
import {
    MembershipPlanResponseFromJSON,
    MembershipPlanResponseFromJSONTyped,
    MembershipPlanResponseToJSON,
    MembershipPlanResponseToJSONTyped,
} from './MembershipPlanResponse';
import type { CustomerCredentialResponse } from './CustomerCredentialResponse';
import {
    CustomerCredentialResponseFromJSON,
    CustomerCredentialResponseFromJSONTyped,
    CustomerCredentialResponseToJSON,
    CustomerCredentialResponseToJSONTyped,
} from './CustomerCredentialResponse';

/**
 * Aggregated membership view for one customer.
 * @export
 * @interface MembershipCustomerViewResponse
 */
export interface MembershipCustomerViewResponse {
    /**
     * 
     * @type {MembershipPlanAssignmentResponse}
     * @memberof MembershipCustomerViewResponse
     */
    activeAssignment?: MembershipPlanAssignmentResponse | null;
    /**
     * 
     * @type {MembershipPlanResponse}
     * @memberof MembershipCustomerViewResponse
     */
    activePlan?: MembershipPlanResponse | null;
    /**
     * 
     * @type {Array<CustomerConsentResponse>}
     * @memberof MembershipCustomerViewResponse
     */
    consents: Array<CustomerConsentResponse>;
    /**
     * 
     * @type {Array<CustomerCredentialResponse>}
     * @memberof MembershipCustomerViewResponse
     */
    credentials: Array<CustomerCredentialResponse>;
    /**
     * 
     * @type {MembershipCustomerResponse}
     * @memberof MembershipCustomerViewResponse
     */
    customer: MembershipCustomerResponse;
    /**
     * 
     * @type {Array<CustomerSubjectResponse>}
     * @memberof MembershipCustomerViewResponse
     */
    subjects: Array<CustomerSubjectResponse>;
}

/**
 * Check if a given object implements the MembershipCustomerViewResponse interface.
 */
export function instanceOfMembershipCustomerViewResponse(value: object): value is MembershipCustomerViewResponse {
    if (!('consents' in value) || value['consents'] === undefined) return false;
    if (!('credentials' in value) || value['credentials'] === undefined) return false;
    if (!('customer' in value) || value['customer'] === undefined) return false;
    if (!('subjects' in value) || value['subjects'] === undefined) return false;
    return true;
}

export function MembershipCustomerViewResponseFromJSON(json: any): MembershipCustomerViewResponse {
    return MembershipCustomerViewResponseFromJSONTyped(json, false);
}

export function MembershipCustomerViewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipCustomerViewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeAssignment': json['activeAssignment'] == null ? undefined : MembershipPlanAssignmentResponseFromJSON(json['activeAssignment']),
        'activePlan': json['activePlan'] == null ? undefined : MembershipPlanResponseFromJSON(json['activePlan']),
        'consents': ((json['consents'] as Array<any>).map(CustomerConsentResponseFromJSON)),
        'credentials': ((json['credentials'] as Array<any>).map(CustomerCredentialResponseFromJSON)),
        'customer': MembershipCustomerResponseFromJSON(json['customer']),
        'subjects': ((json['subjects'] as Array<any>).map(CustomerSubjectResponseFromJSON)),
    };
}

export function MembershipCustomerViewResponseToJSON(json: any): MembershipCustomerViewResponse {
    return MembershipCustomerViewResponseToJSONTyped(json, false);
}

export function MembershipCustomerViewResponseToJSONTyped(value?: MembershipCustomerViewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeAssignment': MembershipPlanAssignmentResponseToJSON(value['activeAssignment']),
        'activePlan': MembershipPlanResponseToJSON(value['activePlan']),
        'consents': ((value['consents'] as Array<any>).map(CustomerConsentResponseToJSON)),
        'credentials': ((value['credentials'] as Array<any>).map(CustomerCredentialResponseToJSON)),
        'customer': MembershipCustomerResponseToJSON(value['customer']),
        'subjects': ((value['subjects'] as Array<any>).map(CustomerSubjectResponseToJSON)),
    };
}

