/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicOrderLine } from './PublicOrderLine';
import {
    PublicOrderLineFromJSON,
    PublicOrderLineFromJSONTyped,
    PublicOrderLineToJSON,
    PublicOrderLineToJSONTyped,
} from './PublicOrderLine';

/**
 * Deliberately tiny.
 * 
 * Where the order goes, which seat serves it, how it is handed over and which
 * channel it belongs to are all resolved from the entry point. `deny_unknown_fields`
 * is what makes that enforceable: a client that tries to add `table_number`
 * gets a 400 instead of being quietly ignored, which is the difference
 * between a contract and a hope.
 * @export
 * @interface PlacePublicOrderRequest
 */
export interface PlacePublicOrderRequest {
    /**
     * The name called out when the order is ready. Optional, and the only
     * personal data this surface accepts.
     * @type {string}
     * @memberof PlacePublicOrderRequest
     */
    customerName?: string | null;
    /**
     * 
     * @type {Array<PublicOrderLine>}
     * @memberof PlacePublicOrderRequest
     */
    items: Array<PublicOrderLine>;
}

/**
 * Check if a given object implements the PlacePublicOrderRequest interface.
 */
export function instanceOfPlacePublicOrderRequest(value: object): value is PlacePublicOrderRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PlacePublicOrderRequestFromJSON(json: any): PlacePublicOrderRequest {
    return PlacePublicOrderRequestFromJSONTyped(json, false);
}

export function PlacePublicOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlacePublicOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerName': json['customer_name'] == null ? undefined : json['customer_name'],
        'items': ((json['items'] as Array<any>).map(PublicOrderLineFromJSON)),
    };
}

export function PlacePublicOrderRequestToJSON(json: any): PlacePublicOrderRequest {
    return PlacePublicOrderRequestToJSONTyped(json, false);
}

export function PlacePublicOrderRequestToJSONTyped(value?: PlacePublicOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_name': value['customerName'],
        'items': ((value['items'] as Array<any>).map(PublicOrderLineToJSON)),
    };
}

