/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * REST-facing mirror of the GraphQL `ProductVariant` type
 * (`order_model::ProductVariant`).
 * 
 * `ProductVariant.metadata` is an `Option<async_graphql::Json<serde_json::Value>>`,
 * which has no `ToSchema` impl and is owned by the GraphQL schema. Since
 * `async_graphql::Json<T>` serializes transparently as `T`, unwrapping it to
 * a plain `Option<serde_json::Value>` here produces an identical JSON wire
 * format while allowing `ToSchema` to be derived.
 * @export
 * @interface ProductVariantRestResponse
 */
export interface ProductVariantRestResponse {
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    id: string;
    /**
     * 
     * @type {any}
     * @memberof ProductVariantRestResponse
     */
    metadata?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantRestResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the ProductVariantRestResponse interface.
 */
export function instanceOfProductVariantRestResponse(value: object): value is ProductVariantRestResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProductVariantRestResponseFromJSON(json: any): ProductVariantRestResponse {
    return ProductVariantRestResponseFromJSONTyped(json, false);
}

export function ProductVariantRestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariantRestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'createdAt': json['createdAt'],
        'id': json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'productId': json['productId'],
        'status': json['status'],
        'tenantId': json['tenantId'],
        'updatedAt': json['updatedAt'],
    };
}

export function ProductVariantRestResponseToJSON(json: any): ProductVariantRestResponse {
    return ProductVariantRestResponseToJSONTyped(json, false);
}

export function ProductVariantRestResponseToJSONTyped(value?: ProductVariantRestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'createdAt': value['createdAt'],
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'productId': value['productId'],
        'status': value['status'],
        'tenantId': value['tenantId'],
        'updatedAt': value['updatedAt'],
    };
}

