/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductVariantOptionResponse } from './ProductVariantOptionResponse';
import {
    ProductVariantOptionResponseFromJSON,
    ProductVariantOptionResponseFromJSONTyped,
    ProductVariantOptionResponseToJSON,
    ProductVariantOptionResponseToJSONTyped,
} from './ProductVariantOptionResponse';
import type { ProductOptionGroupResponse } from './ProductOptionGroupResponse';
import {
    ProductOptionGroupResponseFromJSON,
    ProductOptionGroupResponseFromJSONTyped,
    ProductOptionGroupResponseToJSON,
    ProductOptionGroupResponseToJSONTyped,
} from './ProductOptionGroupResponse';

/**
 * Everything a storefront needs to render a product's choices.
 * @export
 * @interface ProductSelectionsResponse
 */
export interface ProductSelectionsResponse {
    /**
     * 
     * @type {Array<ProductOptionGroupResponse>}
     * @memberof ProductSelectionsResponse
     */
    optionGroups: Array<ProductOptionGroupResponse>;
    /**
     * 
     * @type {string}
     * @memberof ProductSelectionsResponse
     */
    productId: string;
    /**
     * 
     * @type {Array<ProductVariantOptionResponse>}
     * @memberof ProductSelectionsResponse
     */
    variants: Array<ProductVariantOptionResponse>;
}

/**
 * Check if a given object implements the ProductSelectionsResponse interface.
 */
export function instanceOfProductSelectionsResponse(value: object): value is ProductSelectionsResponse {
    if (!('optionGroups' in value) || value['optionGroups'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    return true;
}

export function ProductSelectionsResponseFromJSON(json: any): ProductSelectionsResponse {
    return ProductSelectionsResponseFromJSONTyped(json, false);
}

export function ProductSelectionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSelectionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'optionGroups': ((json['option_groups'] as Array<any>).map(ProductOptionGroupResponseFromJSON)),
        'productId': json['product_id'],
        'variants': ((json['variants'] as Array<any>).map(ProductVariantOptionResponseFromJSON)),
    };
}

export function ProductSelectionsResponseToJSON(json: any): ProductSelectionsResponse {
    return ProductSelectionsResponseToJSONTyped(json, false);
}

export function ProductSelectionsResponseToJSONTyped(value?: ProductSelectionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'option_groups': ((value['optionGroups'] as Array<any>).map(ProductOptionGroupResponseToJSON)),
        'product_id': value['productId'],
        'variants': ((value['variants'] as Array<any>).map(ProductVariantOptionResponseToJSON)),
    };
}

