/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicSelectedOptionResponse } from './PublicSelectedOptionResponse';
import {
    PublicSelectedOptionResponseFromJSON,
    PublicSelectedOptionResponseFromJSONTyped,
    PublicSelectedOptionResponseToJSON,
    PublicSelectedOptionResponseToJSONTyped,
} from './PublicSelectedOptionResponse';

/**
 * 
 * @export
 * @interface PublicOrderItemResponse
 */
export interface PublicOrderItemResponse {
    /**
     * 
     * @type {number}
     * @memberof PublicOrderItemResponse
     */
    baseUnitPriceNanodollar: number;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderItemResponse
     */
    id: string;
    /**
     * Free-text note for this line, e.g. a kitchen instruction.
     * @type {string}
     * @memberof PublicOrderItemResponse
     */
    note?: string | null;
    /**
     * 
     * @type {Array<PublicSelectedOptionResponse>}
     * @memberof PublicOrderItemResponse
     */
    options: Array<PublicSelectedOptionResponse>;
    /**
     * 
     * @type {number}
     * @memberof PublicOrderItemResponse
     */
    optionsTotalNanodollar: number;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderItemResponse
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderItemResponse
     */
    productName: string;
    /**
     * 
     * @type {number}
     * @memberof PublicOrderItemResponse
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof PublicOrderItemResponse
     */
    subtotalNanodollar: number;
    /**
     * 
     * @type {number}
     * @memberof PublicOrderItemResponse
     */
    unitPriceNanodollar: number;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderItemResponse
     */
    variantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderItemResponse
     */
    variantName?: string | null;
}

/**
 * Check if a given object implements the PublicOrderItemResponse interface.
 */
export function instanceOfPublicOrderItemResponse(value: object): value is PublicOrderItemResponse {
    if (!('baseUnitPriceNanodollar' in value) || value['baseUnitPriceNanodollar'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('optionsTotalNanodollar' in value) || value['optionsTotalNanodollar'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('subtotalNanodollar' in value) || value['subtotalNanodollar'] === undefined) return false;
    if (!('unitPriceNanodollar' in value) || value['unitPriceNanodollar'] === undefined) return false;
    return true;
}

export function PublicOrderItemResponseFromJSON(json: any): PublicOrderItemResponse {
    return PublicOrderItemResponseFromJSONTyped(json, false);
}

export function PublicOrderItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOrderItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'baseUnitPriceNanodollar': json['base_unit_price_nanodollar'],
        'id': json['id'],
        'note': json['note'] == null ? undefined : json['note'],
        'options': ((json['options'] as Array<any>).map(PublicSelectedOptionResponseFromJSON)),
        'optionsTotalNanodollar': json['options_total_nanodollar'],
        'productId': json['product_id'],
        'productName': json['product_name'],
        'quantity': json['quantity'],
        'subtotalNanodollar': json['subtotal_nanodollar'],
        'unitPriceNanodollar': json['unit_price_nanodollar'],
        'variantId': json['variant_id'] == null ? undefined : json['variant_id'],
        'variantName': json['variant_name'] == null ? undefined : json['variant_name'],
    };
}

export function PublicOrderItemResponseToJSON(json: any): PublicOrderItemResponse {
    return PublicOrderItemResponseToJSONTyped(json, false);
}

export function PublicOrderItemResponseToJSONTyped(value?: PublicOrderItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base_unit_price_nanodollar': value['baseUnitPriceNanodollar'],
        'id': value['id'],
        'note': value['note'],
        'options': ((value['options'] as Array<any>).map(PublicSelectedOptionResponseToJSON)),
        'options_total_nanodollar': value['optionsTotalNanodollar'],
        'product_id': value['productId'],
        'product_name': value['productName'],
        'quantity': value['quantity'],
        'subtotal_nanodollar': value['subtotalNanodollar'],
        'unit_price_nanodollar': value['unitPriceNanodollar'],
        'variant_id': value['variantId'],
        'variant_name': value['variantName'],
    };
}

