/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuotationItemResponse
 */
export interface QuotationItemResponse {
    /**
     * 
     * @type {number}
     * @memberof QuotationItemResponse
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof QuotationItemResponse
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof QuotationItemResponse
     */
    discountAmount: number;
    /**
     * 
     * @type {number}
     * @memberof QuotationItemResponse
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof QuotationItemResponse
     */
    unitPrice: number;
}

/**
 * Check if a given object implements the QuotationItemResponse interface.
 */
export function instanceOfQuotationItemResponse(value: object): value is QuotationItemResponse {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('discountAmount' in value) || value['discountAmount'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
    return true;
}

export function QuotationItemResponseFromJSON(json: any): QuotationItemResponse {
    return QuotationItemResponseFromJSONTyped(json, false);
}

export function QuotationItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotationItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'description': json['description'],
        'discountAmount': json['discountAmount'],
        'quantity': json['quantity'],
        'unitPrice': json['unitPrice'],
    };
}

export function QuotationItemResponseToJSON(json: any): QuotationItemResponse {
    return QuotationItemResponseToJSONTyped(json, false);
}

export function QuotationItemResponseToJSONTyped(value?: QuotationItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'description': value['description'],
        'discountAmount': value['discountAmount'],
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
    };
}

