/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuotationPdfResponse
 */
export interface QuotationPdfResponse {
    /**
     * 
     * @type {string}
     * @memberof QuotationPdfResponse
     */
    expiresAt: string;
    /**
     * 
     * @type {string}
     * @memberof QuotationPdfResponse
     */
    signedUrl: string;
}

/**
 * Check if a given object implements the QuotationPdfResponse interface.
 */
export function instanceOfQuotationPdfResponse(value: object): value is QuotationPdfResponse {
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('signedUrl' in value) || value['signedUrl'] === undefined) return false;
    return true;
}

export function QuotationPdfResponseFromJSON(json: any): QuotationPdfResponse {
    return QuotationPdfResponseFromJSONTyped(json, false);
}

export function QuotationPdfResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotationPdfResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expiresAt'],
        'signedUrl': json['signedUrl'],
    };
}

export function QuotationPdfResponseToJSON(json: any): QuotationPdfResponse {
    return QuotationPdfResponseToJSONTyped(json, false);
}

export function QuotationPdfResponseToJSONTyped(value?: QuotationPdfResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiresAt': value['expiresAt'],
        'signedUrl': value['signedUrl'],
    };
}

