/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RejectExpenseRequest
 */
export interface RejectExpenseRequest {
    /**
     * 
     * @type {string}
     * @memberof RejectExpenseRequest
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the RejectExpenseRequest interface.
 */
export function instanceOfRejectExpenseRequest(value: object): value is RejectExpenseRequest {
    return true;
}

export function RejectExpenseRequestFromJSON(json: any): RejectExpenseRequest {
    return RejectExpenseRequestFromJSONTyped(json, false);
}

export function RejectExpenseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectExpenseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function RejectExpenseRequestToJSON(json: any): RejectExpenseRequest {
    return RejectExpenseRequestToJSONTyped(json, false);
}

export function RejectExpenseRequestToJSONTyped(value?: RejectExpenseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

