/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationAvailabilityRuleResponse } from './ReservationAvailabilityRuleResponse';
import {
    ReservationAvailabilityRuleResponseFromJSON,
    ReservationAvailabilityRuleResponseFromJSONTyped,
    ReservationAvailabilityRuleResponseToJSON,
    ReservationAvailabilityRuleResponseToJSONTyped,
} from './ReservationAvailabilityRuleResponse';

/**
 * 
 * @export
 * @interface ReservationResourceScheduleResponse
 */
export interface ReservationResourceScheduleResponse {
    /**
     * 
     * @type {string}
     * @memberof ReservationResourceScheduleResponse
     */
    resourceId: string;
    /**
     * 
     * @type {Array<ReservationAvailabilityRuleResponse>}
     * @memberof ReservationResourceScheduleResponse
     */
    rules: Array<ReservationAvailabilityRuleResponse>;
}

/**
 * Check if a given object implements the ReservationResourceScheduleResponse interface.
 */
export function instanceOfReservationResourceScheduleResponse(value: object): value is ReservationResourceScheduleResponse {
    if (!('resourceId' in value) || value['resourceId'] === undefined) return false;
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function ReservationResourceScheduleResponseFromJSON(json: any): ReservationResourceScheduleResponse {
    return ReservationResourceScheduleResponseFromJSONTyped(json, false);
}

export function ReservationResourceScheduleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationResourceScheduleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceId': json['resourceId'],
        'rules': ((json['rules'] as Array<any>).map(ReservationAvailabilityRuleResponseFromJSON)),
    };
}

export function ReservationResourceScheduleResponseToJSON(json: any): ReservationResourceScheduleResponse {
    return ReservationResourceScheduleResponseToJSONTyped(json, false);
}

export function ReservationResourceScheduleResponseToJSONTyped(value?: ReservationResourceScheduleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resourceId': value['resourceId'],
        'rules': ((value['rules'] as Array<any>).map(ReservationAvailabilityRuleResponseToJSON)),
    };
}

