/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationWaitlistStatus } from './ReservationWaitlistStatus';
import {
    ReservationWaitlistStatusFromJSON,
    ReservationWaitlistStatusFromJSONTyped,
    ReservationWaitlistStatusToJSON,
    ReservationWaitlistStatusToJSONTyped,
} from './ReservationWaitlistStatus';

/**
 * A queue entry together with what an operator needs to decide about it.
 * 
 * The two extra fields are computed per read rather than stored: both go
 * stale the moment any other reservation on the slot changes, so a stored
 * copy would be wrong more often than right.
 * @export
 * @interface ReservationWaitlistCandidate
 */
export interface ReservationWaitlistCandidate {
    /**
     * 
     * @type {Date}
     * @memberof ReservationWaitlistCandidate
     */
    closedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    closedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    closedReason?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    convertedReservationId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ReservationWaitlistCandidate
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    customerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    customerPhone?: string;
    /**
     * 
     * @type {Date}
     * @memberof ReservationWaitlistCandidate
     */
    desiredEndsAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReservationWaitlistCandidate
     */
    desiredStartsAt: Date;
    /**
     * When the entry joined the queue. Distinct from `created_at` so that a
     * re-queued request sorts by when it re-queued.
     * @type {Date}
     * @memberof ReservationWaitlistCandidate
     */
    enqueuedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    notes?: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationWaitlistCandidate
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    reservationTypeId: string;
    /**
     * The resource the entry is waiting on. Stored as the empty string when
     * unset, matching `reservation_time_slots`, but exposed as `None` so
     * callers never have to know that.
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    resourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    serviceId?: string;
    /**
     * 
     * @type {ReservationWaitlistStatus}
     * @memberof ReservationWaitlistCandidate
     */
    status: ReservationWaitlistStatus;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    storeId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationWaitlistCandidate
     */
    tenantId: string;
    /**
     * 
     * @type {Date}
     * @memberof ReservationWaitlistCandidate
     */
    updatedAt: Date;
    /**
     * Free groups left on the slot right now, or `None` when no slot row
     * exists for the requested time — an unopened slot is not the same answer
     * as a full one, and only the second is something an operator can wait
     * out.
     * 
     * Groups, not people: `reservation_time_slots.capacity` counts inventory
     * groups and one reservation consumes exactly one of them whatever its
     * party size (`slot_consumption::hold_one_group`). A party of four
     * therefore needs one free group, not four.
     * @type {number}
     * @memberof ReservationWaitlistCandidate
     */
    availableSlotGroups?: number | null;
    /**
     * 1-based place in the queue for this entry's slot, counting only entries
     * still waiting.
     * @type {number}
     * @memberof ReservationWaitlistCandidate
     */
    queuePosition: number;
}



/**
 * Check if a given object implements the ReservationWaitlistCandidate interface.
 */
export function instanceOfReservationWaitlistCandidate(value: object): value is ReservationWaitlistCandidate {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('desiredEndsAt' in value) || value['desiredEndsAt'] === undefined) return false;
    if (!('desiredStartsAt' in value) || value['desiredStartsAt'] === undefined) return false;
    if (!('enqueuedAt' in value) || value['enqueuedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('reservationTypeId' in value) || value['reservationTypeId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('queuePosition' in value) || value['queuePosition'] === undefined) return false;
    return true;
}

export function ReservationWaitlistCandidateFromJSON(json: any): ReservationWaitlistCandidate {
    return ReservationWaitlistCandidateFromJSONTyped(json, false);
}

export function ReservationWaitlistCandidateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationWaitlistCandidate {
    if (json == null) {
        return json;
    }
    return {
        
        'closedAt': json['closedAt'] == null ? undefined : (new Date(json['closedAt'])),
        'closedBy': json['closedBy'] == null ? undefined : json['closedBy'],
        'closedReason': json['closedReason'] == null ? undefined : json['closedReason'],
        'convertedReservationId': json['convertedReservationId'] == null ? undefined : json['convertedReservationId'],
        'createdAt': (new Date(json['createdAt'])),
        'customerEmail': json['customerEmail'] == null ? undefined : json['customerEmail'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'customerName': json['customerName'] == null ? undefined : json['customerName'],
        'customerPhone': json['customerPhone'] == null ? undefined : json['customerPhone'],
        'desiredEndsAt': (new Date(json['desiredEndsAt'])),
        'desiredStartsAt': (new Date(json['desiredStartsAt'])),
        'enqueuedAt': (new Date(json['enqueuedAt'])),
        'id': json['id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'quantity': json['quantity'],
        'reservationTypeId': json['reservationTypeId'],
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'serviceId': json['serviceId'] == null ? undefined : json['serviceId'],
        'status': ReservationWaitlistStatusFromJSON(json['status']),
        'storeId': json['storeId'] == null ? undefined : json['storeId'],
        'tenantId': json['tenantId'],
        'updatedAt': (new Date(json['updatedAt'])),
        'availableSlotGroups': json['availableSlotGroups'] == null ? undefined : json['availableSlotGroups'],
        'queuePosition': json['queuePosition'],
    };
}

export function ReservationWaitlistCandidateToJSON(json: any): ReservationWaitlistCandidate {
    return ReservationWaitlistCandidateToJSONTyped(json, false);
}

export function ReservationWaitlistCandidateToJSONTyped(value?: ReservationWaitlistCandidate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'closedAt': value['closedAt'] == null ? value['closedAt'] : value['closedAt'].toISOString(),
        'closedBy': value['closedBy'],
        'closedReason': value['closedReason'],
        'convertedReservationId': value['convertedReservationId'],
        'createdAt': value['createdAt'].toISOString(),
        'customerEmail': value['customerEmail'],
        'customerId': value['customerId'],
        'customerName': value['customerName'],
        'customerPhone': value['customerPhone'],
        'desiredEndsAt': value['desiredEndsAt'].toISOString(),
        'desiredStartsAt': value['desiredStartsAt'].toISOString(),
        'enqueuedAt': value['enqueuedAt'].toISOString(),
        'id': value['id'],
        'notes': value['notes'],
        'quantity': value['quantity'],
        'reservationTypeId': value['reservationTypeId'],
        'resourceId': value['resourceId'],
        'serviceId': value['serviceId'],
        'status': ReservationWaitlistStatusToJSON(value['status']),
        'storeId': value['storeId'],
        'tenantId': value['tenantId'],
        'updatedAt': value['updatedAt'].toISOString(),
        'availableSlotGroups': value['availableSlotGroups'],
        'queuePosition': value['queuePosition'],
    };
}

