/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReturnOrderRefRequest
 */
export interface ReturnOrderRefRequest {
    /**
     * 
     * @type {string}
     * @memberof ReturnOrderRefRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnOrderRefRequest
     */
    kind: string;
}

/**
 * Check if a given object implements the ReturnOrderRefRequest interface.
 */
export function instanceOfReturnOrderRefRequest(value: object): value is ReturnOrderRefRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function ReturnOrderRefRequestFromJSON(json: any): ReturnOrderRefRequest {
    return ReturnOrderRefRequestFromJSONTyped(json, false);
}

export function ReturnOrderRefRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnOrderRefRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
    };
}

export function ReturnOrderRefRequestToJSON(json: any): ReturnOrderRefRequest {
    return ReturnOrderRefRequestToJSONTyped(json, false);
}

export function ReturnOrderRefRequestToJSONTyped(value?: ReturnOrderRefRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
    };
}

