/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveGolfCaddieRatingRequest
 */
export interface SaveGolfCaddieRatingRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveGolfCaddieRatingRequest
     */
    assignmentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaveGolfCaddieRatingRequest
     */
    caddieProfileId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveGolfCaddieRatingRequest
     */
    comment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaveGolfCaddieRatingRequest
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveGolfCaddieRatingRequest
     */
    reservationId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SaveGolfCaddieRatingRequest
     */
    score: number;
}

/**
 * Check if a given object implements the SaveGolfCaddieRatingRequest interface.
 */
export function instanceOfSaveGolfCaddieRatingRequest(value: object): value is SaveGolfCaddieRatingRequest {
    if (!('caddieProfileId' in value) || value['caddieProfileId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function SaveGolfCaddieRatingRequestFromJSON(json: any): SaveGolfCaddieRatingRequest {
    return SaveGolfCaddieRatingRequestFromJSONTyped(json, false);
}

export function SaveGolfCaddieRatingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveGolfCaddieRatingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assignmentId': json['assignmentId'] == null ? undefined : json['assignmentId'],
        'caddieProfileId': json['caddieProfileId'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'customerId': json['customerId'],
        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'score': json['score'],
    };
}

export function SaveGolfCaddieRatingRequestToJSON(json: any): SaveGolfCaddieRatingRequest {
    return SaveGolfCaddieRatingRequestToJSONTyped(json, false);
}

export function SaveGolfCaddieRatingRequestToJSONTyped(value?: SaveGolfCaddieRatingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignmentId': value['assignmentId'],
        'caddieProfileId': value['caddieProfileId'],
        'comment': value['comment'],
        'customerId': value['customerId'],
        'reservationId': value['reservationId'],
        'score': value['score'],
    };
}

