/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SigningRequestDetailResponse } from './SigningRequestDetailResponse';
import {
    SigningRequestDetailResponseFromJSON,
    SigningRequestDetailResponseFromJSONTyped,
    SigningRequestDetailResponseToJSON,
    SigningRequestDetailResponseToJSONTyped,
} from './SigningRequestDetailResponse';
import type { InvitationDeliveryStatus } from './InvitationDeliveryStatus';
import {
    InvitationDeliveryStatusFromJSON,
    InvitationDeliveryStatusFromJSONTyped,
    InvitationDeliveryStatusToJSON,
    InvitationDeliveryStatusToJSONTyped,
} from './InvitationDeliveryStatus';

/**
 * 
 * @export
 * @interface SendSigningRequestResponse
 */
export interface SendSigningRequestResponse {
    /**
     * 
     * @type {InvitationDeliveryStatus}
     * @memberof SendSigningRequestResponse
     */
    deliveryStatus: InvitationDeliveryStatus;
    /**
     * 
     * @type {Date}
     * @memberof SendSigningRequestResponse
     */
    expiresAt: Date;
    /**
     * Canonical public URL used for both email delivery and manual copy.
     * @type {string}
     * @memberof SendSigningRequestResponse
     */
    invitationUrl: string;
    /**
     * 
     * @type {SigningRequestDetailResponse}
     * @memberof SendSigningRequestResponse
     */
    request: SigningRequestDetailResponse;
    /**
     * Returned only by this send call. The raw token is never persisted.
     * @type {string}
     * @memberof SendSigningRequestResponse
     */
    signingToken: string;
}



/**
 * Check if a given object implements the SendSigningRequestResponse interface.
 */
export function instanceOfSendSigningRequestResponse(value: object): value is SendSigningRequestResponse {
    if (!('deliveryStatus' in value) || value['deliveryStatus'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('invitationUrl' in value) || value['invitationUrl'] === undefined) return false;
    if (!('request' in value) || value['request'] === undefined) return false;
    if (!('signingToken' in value) || value['signingToken'] === undefined) return false;
    return true;
}

export function SendSigningRequestResponseFromJSON(json: any): SendSigningRequestResponse {
    return SendSigningRequestResponseFromJSONTyped(json, false);
}

export function SendSigningRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendSigningRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deliveryStatus': InvitationDeliveryStatusFromJSON(json['deliveryStatus']),
        'expiresAt': (new Date(json['expiresAt'])),
        'invitationUrl': json['invitationUrl'],
        'request': SigningRequestDetailResponseFromJSON(json['request']),
        'signingToken': json['signingToken'],
    };
}

export function SendSigningRequestResponseToJSON(json: any): SendSigningRequestResponse {
    return SendSigningRequestResponseToJSONTyped(json, false);
}

export function SendSigningRequestResponseToJSONTyped(value?: SendSigningRequestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deliveryStatus': InvitationDeliveryStatusToJSON(value['deliveryStatus']),
        'expiresAt': value['expiresAt'].toISOString(),
        'invitationUrl': value['invitationUrl'],
        'request': SigningRequestDetailResponseToJSON(value['request']),
        'signingToken': value['signingToken'],
    };
}

