/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetCustomFieldValuesRequest
 */
export interface SetCustomFieldValuesRequest {
    /**
     * Map of fieldKey to JSON value. `null` clears a stored value.
     * @type {object}
     * @memberof SetCustomFieldValuesRequest
     */
    values: object;
}

/**
 * Check if a given object implements the SetCustomFieldValuesRequest interface.
 */
export function instanceOfSetCustomFieldValuesRequest(value: object): value is SetCustomFieldValuesRequest {
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function SetCustomFieldValuesRequestFromJSON(json: any): SetCustomFieldValuesRequest {
    return SetCustomFieldValuesRequestFromJSONTyped(json, false);
}

export function SetCustomFieldValuesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCustomFieldValuesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['values'],
    };
}

export function SetCustomFieldValuesRequestToJSON(json: any): SetCustomFieldValuesRequest {
    return SetCustomFieldValuesRequestToJSONTyped(json, false);
}

export function SetCustomFieldValuesRequestToJSONTyped(value?: SetCustomFieldValuesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': value['values'],
    };
}

