/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SigningSignerResponse
 */
export interface SigningSignerResponse {
    /**
     * 
     * @type {Date}
     * @memberof SigningSignerResponse
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SigningSignerResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SigningSignerResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SigningSignerResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof SigningSignerResponse
     */
    revokedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SigningSignerResponse
     */
    sentAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SigningSignerResponse
     */
    signerRole: string;
    /**
     * 
     * @type {number}
     * @memberof SigningSignerResponse
     */
    signingOrder: number;
    /**
     * 
     * @type {string}
     * @memberof SigningSignerResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof SigningSignerResponse
     */
    tokenExpiresAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SigningSignerResponse
     */
    viewedAt?: Date | null;
}

/**
 * Check if a given object implements the SigningSignerResponse interface.
 */
export function instanceOfSigningSignerResponse(value: object): value is SigningSignerResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('signerRole' in value) || value['signerRole'] === undefined) return false;
    if (!('signingOrder' in value) || value['signingOrder'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SigningSignerResponseFromJSON(json: any): SigningSignerResponse {
    return SigningSignerResponseFromJSONTyped(json, false);
}

export function SigningSignerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SigningSignerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
        'email': json['email'],
        'id': json['id'],
        'name': json['name'],
        'revokedAt': json['revokedAt'] == null ? undefined : (new Date(json['revokedAt'])),
        'sentAt': json['sentAt'] == null ? undefined : (new Date(json['sentAt'])),
        'signerRole': json['signerRole'],
        'signingOrder': json['signingOrder'],
        'status': json['status'],
        'tokenExpiresAt': json['tokenExpiresAt'] == null ? undefined : (new Date(json['tokenExpiresAt'])),
        'viewedAt': json['viewedAt'] == null ? undefined : (new Date(json['viewedAt'])),
    };
}

export function SigningSignerResponseToJSON(json: any): SigningSignerResponse {
    return SigningSignerResponseToJSONTyped(json, false);
}

export function SigningSignerResponseToJSONTyped(value?: SigningSignerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'revokedAt': value['revokedAt'] == null ? value['revokedAt'] : value['revokedAt'].toISOString(),
        'sentAt': value['sentAt'] == null ? value['sentAt'] : value['sentAt'].toISOString(),
        'signerRole': value['signerRole'],
        'signingOrder': value['signingOrder'],
        'status': value['status'],
        'tokenExpiresAt': value['tokenExpiresAt'] == null ? value['tokenExpiresAt'] : value['tokenExpiresAt'].toISOString(),
        'viewedAt': value['viewedAt'] == null ? value['viewedAt'] : value['viewedAt'].toISOString(),
    };
}

