/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolarBoundary } from './SolarBoundary';
import {
    SolarBoundaryFromJSON,
    SolarBoundaryFromJSONTyped,
    SolarBoundaryToJSON,
    SolarBoundaryToJSONTyped,
} from './SolarBoundary';
import type { ScheduleLocationScope } from './ScheduleLocationScope';
import {
    ScheduleLocationScopeFromJSON,
    ScheduleLocationScopeFromJSONTyped,
    ScheduleLocationScopeToJSON,
    ScheduleLocationScopeToJSONTyped,
} from './ScheduleLocationScope';

/**
 * 
 * @export
 * @interface SolarWindow
 */
export interface SolarWindow {
    /**
     * 
     * @type {SolarBoundary}
     * @memberof SolarWindow
     */
    earliestStart?: SolarBoundary | null;
    /**
     * 
     * @type {SolarBoundary}
     * @memberof SolarWindow
     */
    latestStart?: SolarBoundary | null;
    /**
     * 
     * @type {ScheduleLocationScope}
     * @memberof SolarWindow
     */
    locationScope: ScheduleLocationScope;
}



/**
 * Check if a given object implements the SolarWindow interface.
 */
export function instanceOfSolarWindow(value: object): value is SolarWindow {
    if (!('locationScope' in value) || value['locationScope'] === undefined) return false;
    return true;
}

export function SolarWindowFromJSON(json: any): SolarWindow {
    return SolarWindowFromJSONTyped(json, false);
}

export function SolarWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolarWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'earliestStart': json['earliestStart'] == null ? undefined : SolarBoundaryFromJSON(json['earliestStart']),
        'latestStart': json['latestStart'] == null ? undefined : SolarBoundaryFromJSON(json['latestStart']),
        'locationScope': ScheduleLocationScopeFromJSON(json['locationScope']),
    };
}

export function SolarWindowToJSON(json: any): SolarWindow {
    return SolarWindowToJSONTyped(json, false);
}

export function SolarWindowToJSONTyped(value?: SolarWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'earliestStart': SolarBoundaryToJSON(value['earliestStart']),
        'latestStart': SolarBoundaryToJSON(value['latestStart']),
        'locationScope': ScheduleLocationScopeToJSON(value['locationScope']),
    };
}

