/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaffPayrollEstimate
 */
export interface StaffPayrollEstimate {
    /**
     * 
     * @type {string}
     * @memberof StaffPayrollEstimate
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof StaffPayrollEstimate
     */
    estimatedAmountYen: number;
    /**
     * 
     * @type {number}
     * @memberof StaffPayrollEstimate
     */
    monthlyIncomeTargetYen?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StaffPayrollEstimate
     */
    period: string;
    /**
     * 
     * @type {number}
     * @memberof StaffPayrollEstimate
     */
    shiftedDays: number;
    /**
     * 
     * @type {string}
     * @memberof StaffPayrollEstimate
     */
    staffId: string;
    /**
     * 
     * @type {number}
     * @memberof StaffPayrollEstimate
     */
    targetGapYen?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StaffPayrollEstimate
     */
    tenantId: string;
    /**
     * 
     * @type {number}
     * @memberof StaffPayrollEstimate
     */
    workedDays: number;
    /**
     * 
     * @type {number}
     * @memberof StaffPayrollEstimate
     */
    workedMinutes: number;
}

/**
 * Check if a given object implements the StaffPayrollEstimate interface.
 */
export function instanceOfStaffPayrollEstimate(value: object): value is StaffPayrollEstimate {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('estimatedAmountYen' in value) || value['estimatedAmountYen'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('shiftedDays' in value) || value['shiftedDays'] === undefined) return false;
    if (!('staffId' in value) || value['staffId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('workedDays' in value) || value['workedDays'] === undefined) return false;
    if (!('workedMinutes' in value) || value['workedMinutes'] === undefined) return false;
    return true;
}

export function StaffPayrollEstimateFromJSON(json: any): StaffPayrollEstimate {
    return StaffPayrollEstimateFromJSONTyped(json, false);
}

export function StaffPayrollEstimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffPayrollEstimate {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'estimatedAmountYen': json['estimatedAmountYen'],
        'monthlyIncomeTargetYen': json['monthlyIncomeTargetYen'] == null ? undefined : json['monthlyIncomeTargetYen'],
        'period': json['period'],
        'shiftedDays': json['shiftedDays'],
        'staffId': json['staffId'],
        'targetGapYen': json['targetGapYen'] == null ? undefined : json['targetGapYen'],
        'tenantId': json['tenantId'],
        'workedDays': json['workedDays'],
        'workedMinutes': json['workedMinutes'],
    };
}

export function StaffPayrollEstimateToJSON(json: any): StaffPayrollEstimate {
    return StaffPayrollEstimateToJSONTyped(json, false);
}

export function StaffPayrollEstimateToJSONTyped(value?: StaffPayrollEstimate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'estimatedAmountYen': value['estimatedAmountYen'],
        'monthlyIncomeTargetYen': value['monthlyIncomeTargetYen'],
        'period': value['period'],
        'shiftedDays': value['shiftedDays'],
        'staffId': value['staffId'],
        'targetGapYen': value['targetGapYen'],
        'tenantId': value['tenantId'],
        'workedDays': value['workedDays'],
        'workedMinutes': value['workedMinutes'],
    };
}

