/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaffProfileView } from './StaffProfileView';
import {
    StaffProfileViewFromJSON,
    StaffProfileViewFromJSONTyped,
    StaffProfileViewToJSON,
    StaffProfileViewToJSONTyped,
} from './StaffProfileView';

/**
 * 
 * @export
 * @interface StaffProfileListResponse
 */
export interface StaffProfileListResponse {
    /**
     * 
     * @type {Array<StaffProfileView>}
     * @memberof StaffProfileListResponse
     */
    items: Array<StaffProfileView>;
}

/**
 * Check if a given object implements the StaffProfileListResponse interface.
 */
export function instanceOfStaffProfileListResponse(value: object): value is StaffProfileListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function StaffProfileListResponseFromJSON(json: any): StaffProfileListResponse {
    return StaffProfileListResponseFromJSONTyped(json, false);
}

export function StaffProfileListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffProfileListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(StaffProfileViewFromJSON)),
    };
}

export function StaffProfileListResponseToJSON(json: any): StaffProfileListResponse {
    return StaffProfileListResponseToJSONTyped(json, false);
}

export function StaffProfileListResponseToJSONTyped(value?: StaffProfileListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(StaffProfileViewToJSON)),
    };
}

