/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StaffPreferredTimeBand = {
    Any: 'any',
    Morning: 'morning',
    Afternoon: 'afternoon',
    Evening: 'evening'
} as const;
export type StaffPreferredTimeBand = typeof StaffPreferredTimeBand[keyof typeof StaffPreferredTimeBand];


export function instanceOfStaffPreferredTimeBand(value: any): boolean {
    for (const key in StaffPreferredTimeBand) {
        if (Object.prototype.hasOwnProperty.call(StaffPreferredTimeBand, key)) {
            if (StaffPreferredTimeBand[key as keyof typeof StaffPreferredTimeBand] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StaffPreferredTimeBandFromJSON(json: any): StaffPreferredTimeBand {
    return StaffPreferredTimeBandFromJSONTyped(json, false);
}

export function StaffPreferredTimeBandFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffPreferredTimeBand {
    return json as StaffPreferredTimeBand;
}

export function StaffPreferredTimeBandToJSON(value?: StaffPreferredTimeBand | null): any {
    return value as any;
}

export function StaffPreferredTimeBandToJSONTyped(value: any, ignoreDiscriminator: boolean): StaffPreferredTimeBand {
    return value as StaffPreferredTimeBand;
}

