/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A stock balance as the ERP context actually knows it.
 * 
 * The nullable fields below have **no source in this context** and are
 * therefore always `null` (#724 W4). They are kept as explicit nulls rather
 * than removed so a client can tell "not provided" from "zero"; previously
 * they carried synthesized values that read as real data:
 * 
 * - `product_name` was the SKU. The ERP context stores no product name; the
 *   SKU is the identity here. Resolving a name would mean joining
 *   `order_products` by SKU, which spans two different tenant-scoping
 *   regimes (this repository is bound to the process root tenant, that one
 *   is per-request), so it is deliberately not done here.
 * - `quantity_available` was `quantity_on_hand` and `quantity_allocated` was
 *   `0`. The ERP context models no allocation at all, so neither can be
 *   answered. Allocation lives in commerce `product_stocks`.
 * - `source_delivery_id` was already always null. A balance is the sum of
 *   many receipts, so a single delivery cannot identify it; the per-receipt
 *   link lives on stock movements.
 * 
 * See `docs/domain/inventory-source-of-truth.md`.
 * @export
 * @interface StockLevelResponse
 */
export interface StockLevelResponse {
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    lastUpdatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    productName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StockLevelResponse
     */
    quantityAllocated?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockLevelResponse
     */
    quantityAvailable?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockLevelResponse
     */
    quantityOnHand: number;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    sku: string;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    skuCode: string;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    sourceDeliveryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    stockItemId: string;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    warehouseId: string;
    /**
     * 
     * @type {string}
     * @memberof StockLevelResponse
     */
    warehouseName: string;
}

/**
 * Check if a given object implements the StockLevelResponse interface.
 */
export function instanceOfStockLevelResponse(value: object): value is StockLevelResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastUpdatedAt' in value) || value['lastUpdatedAt'] === undefined) return false;
    if (!('quantityOnHand' in value) || value['quantityOnHand'] === undefined) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    if (!('skuCode' in value) || value['skuCode'] === undefined) return false;
    if (!('stockItemId' in value) || value['stockItemId'] === undefined) return false;
    if (!('warehouseId' in value) || value['warehouseId'] === undefined) return false;
    if (!('warehouseName' in value) || value['warehouseName'] === undefined) return false;
    return true;
}

export function StockLevelResponseFromJSON(json: any): StockLevelResponse {
    return StockLevelResponseFromJSONTyped(json, false);
}

export function StockLevelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockLevelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lastUpdatedAt': json['lastUpdatedAt'],
        'productName': json['productName'] == null ? undefined : json['productName'],
        'quantityAllocated': json['quantityAllocated'] == null ? undefined : json['quantityAllocated'],
        'quantityAvailable': json['quantityAvailable'] == null ? undefined : json['quantityAvailable'],
        'quantityOnHand': json['quantityOnHand'],
        'sku': json['sku'],
        'skuCode': json['skuCode'],
        'sourceDeliveryId': json['sourceDeliveryId'] == null ? undefined : json['sourceDeliveryId'],
        'stockItemId': json['stockItemId'],
        'warehouseId': json['warehouseId'],
        'warehouseName': json['warehouseName'],
    };
}

export function StockLevelResponseToJSON(json: any): StockLevelResponse {
    return StockLevelResponseToJSONTyped(json, false);
}

export function StockLevelResponseToJSONTyped(value?: StockLevelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lastUpdatedAt': value['lastUpdatedAt'],
        'productName': value['productName'],
        'quantityAllocated': value['quantityAllocated'],
        'quantityAvailable': value['quantityAvailable'],
        'quantityOnHand': value['quantityOnHand'],
        'sku': value['sku'],
        'skuCode': value['skuCode'],
        'sourceDeliveryId': value['sourceDeliveryId'],
        'stockItemId': value['stockItemId'],
        'warehouseId': value['warehouseId'],
        'warehouseName': value['warehouseName'],
    };
}

