/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceTimeSlot } from './ResourceTimeSlot';
import {
    ResourceTimeSlotFromJSON,
    ResourceTimeSlotFromJSONTyped,
    ResourceTimeSlotToJSON,
    ResourceTimeSlotToJSONTyped,
} from './ResourceTimeSlot';

/**
 * 
 * @export
 * @interface StorefrontResourceTimeSlotListResponse
 */
export interface StorefrontResourceTimeSlotListResponse {
    /**
     * 
     * @type {Date}
     * @memberof StorefrontResourceTimeSlotListResponse
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof StorefrontResourceTimeSlotListResponse
     */
    resourceId: string;
    /**
     * 
     * @type {Array<ResourceTimeSlot>}
     * @memberof StorefrontResourceTimeSlotListResponse
     */
    slots: Array<ResourceTimeSlot>;
    /**
     * 
     * @type {string}
     * @memberof StorefrontResourceTimeSlotListResponse
     */
    timezone: string;
}

/**
 * Check if a given object implements the StorefrontResourceTimeSlotListResponse interface.
 */
export function instanceOfStorefrontResourceTimeSlotListResponse(value: object): value is StorefrontResourceTimeSlotListResponse {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('resourceId' in value) || value['resourceId'] === undefined) return false;
    if (!('slots' in value) || value['slots'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    return true;
}

export function StorefrontResourceTimeSlotListResponseFromJSON(json: any): StorefrontResourceTimeSlotListResponse {
    return StorefrontResourceTimeSlotListResponseFromJSONTyped(json, false);
}

export function StorefrontResourceTimeSlotListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorefrontResourceTimeSlotListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'resourceId': json['resourceId'],
        'slots': ((json['slots'] as Array<any>).map(ResourceTimeSlotFromJSON)),
        'timezone': json['timezone'],
    };
}

export function StorefrontResourceTimeSlotListResponseToJSON(json: any): StorefrontResourceTimeSlotListResponse {
    return StorefrontResourceTimeSlotListResponseToJSONTyped(json, false);
}

export function StorefrontResourceTimeSlotListResponseToJSONTyped(value?: StorefrontResourceTimeSlotListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'resourceId': value['resourceId'],
        'slots': ((value['slots'] as Array<any>).map(ResourceTimeSlotToJSON)),
        'timezone': value['timezone'],
    };
}

