/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreResponse } from './StoreResponse';
import {
    StoreResponseFromJSON,
    StoreResponseFromJSONTyped,
    StoreResponseToJSON,
    StoreResponseToJSONTyped,
} from './StoreResponse';

/**
 * 
 * @export
 * @interface StoreListResponse
 */
export interface StoreListResponse {
    /**
     * 
     * @type {Array<StoreResponse>}
     * @memberof StoreListResponse
     */
    items: Array<StoreResponse>;
}

/**
 * Check if a given object implements the StoreListResponse interface.
 */
export function instanceOfStoreListResponse(value: object): value is StoreListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function StoreListResponseFromJSON(json: any): StoreListResponse {
    return StoreListResponseFromJSONTyped(json, false);
}

export function StoreListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(StoreResponseFromJSON)),
    };
}

export function StoreListResponseToJSON(json: any): StoreListResponse {
    return StoreListResponseToJSONTyped(json, false);
}

export function StoreListResponseToJSONTyped(value?: StoreListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(StoreResponseToJSON)),
    };
}

