/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreKitListPublicProductResponseItemsInner } from './StoreKitListPublicProductResponseItemsInner';
import {
    StoreKitListPublicProductResponseItemsInnerFromJSON,
    StoreKitListPublicProductResponseItemsInnerFromJSONTyped,
    StoreKitListPublicProductResponseItemsInnerToJSON,
    StoreKitListPublicProductResponseItemsInnerToJSONTyped,
} from './StoreKitListPublicProductResponseItemsInner';

/**
 * 
 * @export
 * @interface StoreKitListPublicProductResponse
 */
export interface StoreKitListPublicProductResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StoreKitListPublicProductResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<StoreKitListPublicProductResponseItemsInner>}
     * @memberof StoreKitListPublicProductResponse
     */
    items: Array<StoreKitListPublicProductResponseItemsInner>;
    /**
     * 
     * @type {number}
     * @memberof StoreKitListPublicProductResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof StoreKitListPublicProductResponse
     */
    offset: number;
    /**
     * 絞り込み後の総件数。ページの件数ではない (PLT-4050)。
     * 
     * `null` は「この一覧は総件数を数えていない」であって 0 ではない。総件
     * 数には母集合を1回余分に数える COUNT が要るので、必要とする一覧だけが
     * 値を載せる。今のところ載るのは `GET /v1/storekit/customers` だけ。
     * @type {number}
     * @memberof StoreKitListPublicProductResponse
     */
    total?: number | null;
}

/**
 * Check if a given object implements the StoreKitListPublicProductResponse interface.
 */
export function instanceOfStoreKitListPublicProductResponse(value: object): value is StoreKitListPublicProductResponse {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function StoreKitListPublicProductResponseFromJSON(json: any): StoreKitListPublicProductResponse {
    return StoreKitListPublicProductResponseFromJSONTyped(json, false);
}

export function StoreKitListPublicProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreKitListPublicProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'items': ((json['items'] as Array<any>).map(StoreKitListPublicProductResponseItemsInnerFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function StoreKitListPublicProductResponseToJSON(json: any): StoreKitListPublicProductResponse {
    return StoreKitListPublicProductResponseToJSONTyped(json, false);
}

export function StoreKitListPublicProductResponseToJSONTyped(value?: StoreKitListPublicProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_more': value['hasMore'],
        'items': ((value['items'] as Array<any>).map(StoreKitListPublicProductResponseItemsInnerToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

