/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationResourceType } from './ReservationResourceType';
import {
    ReservationResourceTypeFromJSON,
    ReservationResourceTypeFromJSONTyped,
    ReservationResourceTypeToJSON,
    ReservationResourceTypeToJSONTyped,
} from './ReservationResourceType';

/**
 * 
 * @export
 * @interface UpdateReservationResourceRequest
 */
export interface UpdateReservationResourceRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateReservationResourceRequest
     */
    active?: boolean | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateReservationResourceRequest
     */
    customFieldsJson?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateReservationResourceRequest
     */
    metadataJson?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateReservationResourceRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateReservationResourceRequest
     */
    resourceModel?: string | null;
    /**
     * 
     * @type {ReservationResourceType}
     * @memberof UpdateReservationResourceRequest
     */
    resourceType?: ReservationResourceType | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateReservationResourceRequest
     */
    storeId?: string | null;
}



/**
 * Check if a given object implements the UpdateReservationResourceRequest interface.
 */
export function instanceOfUpdateReservationResourceRequest(value: object): value is UpdateReservationResourceRequest {
    return true;
}

export function UpdateReservationResourceRequestFromJSON(json: any): UpdateReservationResourceRequest {
    return UpdateReservationResourceRequestFromJSONTyped(json, false);
}

export function UpdateReservationResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReservationResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'customFieldsJson': json['customFieldsJson'] == null ? undefined : json['customFieldsJson'],
        'metadataJson': json['metadataJson'] == null ? undefined : json['metadataJson'],
        'name': json['name'] == null ? undefined : json['name'],
        'resourceModel': json['resourceModel'] == null ? undefined : json['resourceModel'],
        'resourceType': json['resourceType'] == null ? undefined : ReservationResourceTypeFromJSON(json['resourceType']),
        'storeId': json['storeId'] == null ? undefined : json['storeId'],
    };
}

export function UpdateReservationResourceRequestToJSON(json: any): UpdateReservationResourceRequest {
    return UpdateReservationResourceRequestToJSONTyped(json, false);
}

export function UpdateReservationResourceRequestToJSONTyped(value?: UpdateReservationResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'customFieldsJson': value['customFieldsJson'],
        'metadataJson': value['metadataJson'],
        'name': value['name'],
        'resourceModel': value['resourceModel'],
        'resourceType': ReservationResourceTypeToJSON(value['resourceType']),
        'storeId': value['storeId'],
    };
}

