/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceResponse } from './InvoiceResponse';
import {
    InvoiceResponseFromJSON,
    InvoiceResponseFromJSONTyped,
    InvoiceResponseToJSON,
    InvoiceResponseToJSONTyped,
} from './InvoiceResponse';

/**
 * 
 * @export
 * @interface VoidInvoiceResponse
 */
export interface VoidInvoiceResponse {
    /**
     * 
     * @type {string}
     * @memberof VoidInvoiceResponse
     */
    correctionId: string;
    /**
     * 
     * @type {InvoiceResponse}
     * @memberof VoidInvoiceResponse
     */
    invoice: InvoiceResponse;
    /**
     * 
     * @type {boolean}
     * @memberof VoidInvoiceResponse
     */
    replayed: boolean;
    /**
     * 
     * @type {string}
     * @memberof VoidInvoiceResponse
     */
    reversalOn: string | null;
    /**
     * 
     * @type {number}
     * @memberof VoidInvoiceResponse
     */
    reversedJournalCount: number;
}

/**
 * Check if a given object implements the VoidInvoiceResponse interface.
 */
export function instanceOfVoidInvoiceResponse(value: object): value is VoidInvoiceResponse {
    if (!('correctionId' in value) || value['correctionId'] === undefined) return false;
    if (!('invoice' in value) || value['invoice'] === undefined) return false;
    if (!('replayed' in value) || value['replayed'] === undefined) return false;
    if (!('reversalOn' in value) || value['reversalOn'] === undefined) return false;
    if (!('reversedJournalCount' in value) || value['reversedJournalCount'] === undefined) return false;
    return true;
}

export function VoidInvoiceResponseFromJSON(json: any): VoidInvoiceResponse {
    return VoidInvoiceResponseFromJSONTyped(json, false);
}

export function VoidInvoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoidInvoiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'correctionId': json['correctionId'],
        'invoice': InvoiceResponseFromJSON(json['invoice']),
        'replayed': json['replayed'],
        'reversalOn': json['reversalOn'],
        'reversedJournalCount': json['reversedJournalCount'],
    };
}

export function VoidInvoiceResponseToJSON(json: any): VoidInvoiceResponse {
    return VoidInvoiceResponseToJSONTyped(json, false);
}

export function VoidInvoiceResponseToJSONTyped(value?: VoidInvoiceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correctionId': value['correctionId'],
        'invoice': InvoiceResponseToJSON(value['invoice']),
        'replayed': value['replayed'],
        'reversalOn': value['reversalOn'],
        'reversedJournalCount': value['reversedJournalCount'],
    };
}

