/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignMembershipPlanRequest {
    #[serde(
        rename = "note",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub note: Option<Option<String>>,
    /// Class to join directly. Mutually exclusive with `productId`; one of the two is required.
    #[serde(
        rename = "planId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub plan_id: Option<Option<String>>,
    /// Product being sold. Mutually exclusive with `planId`.
    #[serde(
        rename = "productId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub product_id: Option<Option<String>>,
    /// YYYY-MM-DD (default today)
    #[serde(
        rename = "startedOn",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub started_on: Option<Option<String>>,
}

impl AssignMembershipPlanRequest {
    pub fn new() -> AssignMembershipPlanRequest {
        AssignMembershipPlanRequest {
            note: None,
            plan_id: None,
            product_id: None,
            started_on: None,
        }
    }
}
