/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoAssignCaddiesRequest {
    /// 対象となるテナントローカル日付。
    #[serde(rename = "date")]
    pub date: String,
    /// true なら計画のみ返し、割当は保存しない
    #[serde(rename = "dryRun", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
    /// `date` と午前・午後を定義する IANA timezone。省略時は従来の Asia/Tokyo。
    #[serde(
        rename = "timezone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timezone: Option<Option<String>>,
}

impl AutoAssignCaddiesRequest {
    pub fn new(date: String) -> AutoAssignCaddiesRequest {
        AutoAssignCaddiesRequest {
            date,
            dry_run: None,
            timezone: None,
        }
    }
}
