/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgeMapping {
    #[serde(rename = "fields")]
    pub fields: Vec<models::BridgeMappingField>,
    #[serde(
        rename = "llmProposal",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub llm_proposal: Option<Option<serde_json::Value>>,
}

impl BridgeMapping {
    pub fn new(fields: Vec<models::BridgeMappingField>) -> BridgeMapping {
        BridgeMapping {
            fields,
            llm_proposal: None,
        }
    }
}
