/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BridgeTargetFieldView : The wire shape of one target property, shared by the API and the UI so the browser never keeps its own copy of the field list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgeTargetFieldView {
    #[serde(rename = "aliases")]
    pub aliases: Vec<String>,
    /// Accepted spellings for `kind == \"enum\"`, otherwise empty.
    #[serde(rename = "allowed")]
    pub allowed: Vec<String>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "required")]
    pub required: bool,
}

impl BridgeTargetFieldView {
    /// The wire shape of one target property, shared by the API and the UI so the browser never keeps its own copy of the field list.
    pub fn new(
        aliases: Vec<String>,
        allowed: Vec<String>,
        key: String,
        kind: String,
        label: String,
        required: bool,
    ) -> BridgeTargetFieldView {
        BridgeTargetFieldView {
            aliases,
            allowed,
            key,
            kind,
            label,
            required,
        }
    }
}
