/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseCustomerClientAffiliationRequest {
    #[serde(rename = "validTo")]
    pub valid_to: String,
}

impl CloseCustomerClientAffiliationRequest {
    pub fn new(valid_to: String) -> CloseCustomerClientAffiliationRequest {
        CloseCustomerClientAffiliationRequest { valid_to }
    }
}
