/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponResponse {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "discount_type")]
    pub discount_type: String,
    #[serde(rename = "discount_value")]
    pub discount_value: i32,
    #[serde(
        rename = "exclusion_group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub exclusion_group: Option<Option<String>>,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(
        rename = "minimum_order_amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub minimum_order_amount: Option<Option<i64>>,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(
        rename = "usage_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub usage_limit: Option<Option<i32>>,
    #[serde(rename = "use_per_user")]
    pub use_per_user: bool,
    #[serde(rename = "used_count")]
    pub used_count: i32,
}

impl CouponResponse {
    pub fn new(
        code: String,
        created_at: String,
        currency: String,
        discount_type: String,
        discount_value: i32,
        id: String,
        is_active: bool,
        tenant_id: String,
        updated_at: String,
        use_per_user: bool,
        used_count: i32,
    ) -> CouponResponse {
        CouponResponse {
            code,
            created_at,
            currency,
            discount_type,
            discount_value,
            exclusion_group: None,
            expires_at: None,
            id,
            is_active,
            minimum_order_amount: None,
            tenant_id,
            updated_at,
            usage_limit: None,
            use_per_user,
            used_count,
        }
    }
}
