/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.7
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateStockOutboundRequest {
    #[serde(
        rename = "operatorId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub operator_id: Option<Option<String>>,
    #[serde(rename = "quantity")]
    pub quantity: i64,
    #[serde(
        rename = "referenceId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reference_id: Option<Option<String>>,
    #[serde(
        rename = "referenceType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reference_type: Option<Option<String>>,
    #[serde(rename = "sku")]
    pub sku: String,
    #[serde(
        rename = "warehouseId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub warehouse_id: Option<Option<String>>,
}

impl CreateStockOutboundRequest {
    pub fn new(quantity: i64, sku: String) -> CreateStockOutboundRequest {
        CreateStockOutboundRequest {
            operator_id: None,
            quantity,
            reference_id: None,
            reference_type: None,
            sku,
            warehouse_id: None,
        }
    }
}
