/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrderRequest {
    #[serde(
        rename = "clientEmail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_email: Option<Option<String>>,
    #[serde(rename = "clientId")]
    pub client_id: String,
    #[serde(
        rename = "clientName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_name: Option<Option<String>>,
    #[serde(
        rename = "currency",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency: Option<Option<String>>,
    #[serde(rename = "items")]
    pub items: Vec<models::CreateOrderItemRequest>,
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(
        rename = "orderNumber",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub order_number: Option<Option<String>>,
    #[serde(
        rename = "source",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source: Option<Option<String>>,
    #[serde(
        rename = "squareOrderId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub square_order_id: Option<Option<String>>,
    #[serde(
        rename = "squarePaymentId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub square_payment_id: Option<Option<String>>,
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<String>>,
    #[serde(
        rename = "taxAmount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_amount: Option<Option<i64>>,
}

impl CreateOrderRequest {
    pub fn new(
        client_id: String,
        items: Vec<models::CreateOrderItemRequest>,
    ) -> CreateOrderRequest {
        CreateOrderRequest {
            client_email: None,
            client_id,
            client_name: None,
            currency: None,
            items,
            notes: None,
            order_number: None,
            source: None,
            square_order_id: None,
            square_payment_id: None,
            status: None,
            tax_amount: None,
        }
    }
}
