/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateReturnLineRequest {
    #[serde(rename = "purchasedQuantity")]
    pub purchased_quantity: i32,
    #[serde(rename = "requestedQuantity")]
    pub requested_quantity: i32,
    #[serde(
        rename = "sku",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sku: Option<Option<String>>,
    #[serde(rename = "sourceLine")]
    pub source_line: Box<models::ReturnLineRefRequest>,
}

impl CreateReturnLineRequest {
    pub fn new(
        purchased_quantity: i32,
        requested_quantity: i32,
        source_line: models::ReturnLineRefRequest,
    ) -> CreateReturnLineRequest {
        CreateReturnLineRequest {
            purchased_quantity,
            requested_quantity,
            sku: None,
            source_line: Box::new(source_line),
        }
    }
}
