/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerContactListResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::CustomerContactResponse>,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "offset")]
    pub offset: i32,
    /// 絞り込んだ結果の総件数。返した `items` の数ではない。
    #[serde(rename = "total")]
    pub total: i64,
}

impl CustomerContactListResponse {
    pub fn new(
        items: Vec<models::CustomerContactResponse>,
        limit: i32,
        offset: i32,
        total: i64,
    ) -> CustomerContactListResponse {
        CustomerContactListResponse {
            items,
            limit,
            offset,
            total,
        }
    }
}
