/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmploymentStatus : Where a staff member stands with the employer, independent of industry.  This is not the same axis as a leave request: a leave request is one day off with a decision on it, while `OnLeave` is a months-long absence the roster has to plan around.
/// Where a staff member stands with the employer, independent of industry.  This is not the same axis as a leave request: a leave request is one day off with a decision on it, while `OnLeave` is a months-long absence the roster has to plan around.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EmploymentStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "on_leave")]
    OnLeave,
    #[serde(rename = "retired")]
    Retired,
}

impl std::fmt::Display for EmploymentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "active"),
            Self::OnLeave => write!(f, "on_leave"),
            Self::Retired => write!(f, "retired"),
        }
    }
}

impl Default for EmploymentStatus {
    fn default() -> EmploymentStatus {
        Self::Active
    }
}
