/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GolfCourse {
    #[serde(
        rename = "businessHoursJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_hours_json: Option<Option<serde_json::Value>>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "extensionKey")]
    pub extension_key: String,
    #[serde(rename = "holeCount")]
    pub hole_count: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "shortName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub short_name: Option<Option<String>>,
    #[serde(rename = "startIntervalMinutes")]
    pub start_interval_minutes: i32,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "timezone")]
    pub timezone: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl GolfCourse {
    pub fn new(
        created_at: String,
        extension_key: String,
        hole_count: i32,
        id: String,
        is_active: bool,
        name: String,
        start_interval_minutes: i32,
        tenant_id: String,
        timezone: String,
        updated_at: String,
    ) -> GolfCourse {
        GolfCourse {
            business_hours_json: None,
            created_at,
            extension_key,
            hole_count,
            id,
            is_active,
            name,
            short_name: None,
            start_interval_minutes,
            tenant_id,
            timezone,
            updated_at,
        }
    }
}
