/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GolfCourseResource {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(
        rename = "attributesJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attributes_json: Option<Option<serde_json::Value>>,
    #[serde(rename = "capacity")]
    pub capacity: i32,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "extensionKey")]
    pub extension_key: String,
    /// どのコースの受付枠か。storefront はこれで「別コースの枠」を落とす。  列が空のときは `attributes_json` / `metadata_json` の `golfCourseId` から埋める（列が無かった頃に CourseBoard が使っていた規約）。
    #[serde(
        rename = "golfCourseId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub golf_course_id: Option<Option<String>>,
    #[serde(
        rename = "holeCount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub hole_count: Option<Option<i32>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "metadataJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata_json: Option<Option<serde_json::Value>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "par",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub par: Option<Option<i32>>,
    #[serde(
        rename = "reservationResourceId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reservation_resource_id: Option<Option<String>>,
    #[serde(rename = "resourceCode")]
    pub resource_code: String,
    #[serde(rename = "resourceKind")]
    pub resource_kind: models::GolfResourceKind,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl GolfCourseResource {
    pub fn new(
        active: bool,
        capacity: i32,
        created_at: String,
        extension_key: String,
        id: String,
        name: String,
        resource_code: String,
        resource_kind: models::GolfResourceKind,
        tenant_id: String,
        updated_at: String,
    ) -> GolfCourseResource {
        GolfCourseResource {
            active,
            attributes_json: None,
            capacity,
            created_at,
            extension_key,
            golf_course_id: None,
            hole_count: None,
            id,
            metadata_json: None,
            name,
            par: None,
            reservation_resource_id: None,
            resource_code,
            resource_kind,
            tenant_id,
            updated_at,
        }
    }
}
