/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GolfCaddieAssignment {
    #[serde(rename = "assignmentRole")]
    pub assignment_role: String,
    #[serde(rename = "caddieProfileId")]
    pub caddie_profile_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "extensionKey")]
    pub extension_key: String,
    #[serde(rename = "feeAmount")]
    pub fee_amount: i64,
    #[serde(rename = "feeCurrency")]
    pub fee_currency: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "metadataJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata_json: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "nominatedBy",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nominated_by: Option<Option<String>>,
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(
        rename = "recommendationScore",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub recommendation_score: Option<Option<i32>>,
    #[serde(
        rename = "reservationId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reservation_id: Option<Option<String>>,
    #[serde(
        rename = "roundReference",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub round_reference: Option<Option<String>>,
    #[serde(rename = "scheduledAt")]
    pub scheduled_at: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl GolfCaddieAssignment {
    pub fn new(
        assignment_role: String,
        caddie_profile_id: String,
        created_at: String,
        extension_key: String,
        fee_amount: i64,
        fee_currency: String,
        id: String,
        scheduled_at: String,
        status: String,
        tenant_id: String,
        updated_at: String,
    ) -> GolfCaddieAssignment {
        GolfCaddieAssignment {
            assignment_role,
            caddie_profile_id,
            created_at,
            extension_key,
            fee_amount,
            fee_currency,
            id,
            metadata_json: None,
            nominated_by: None,
            notes: None,
            recommendation_score: None,
            reservation_id: None,
            round_reference: None,
            scheduled_at,
            status,
            tenant_id,
            updated_at,
        }
    }
}
