/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceBillToEvidenceResponseOneOf1 {
    #[serde(rename = "kind")]
    pub kind: Kind,
}

impl InvoiceBillToEvidenceResponseOneOf1 {
    pub fn new(kind: Kind) -> InvoiceBillToEvidenceResponseOneOf1 {
        InvoiceBillToEvidenceResponseOneOf1 { kind }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "direct")]
    Direct,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Direct
    }
}
