/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvoiceBillToRequestOneOf2 : 顧客台帳にも取引先にも無い相手への単発請求。  識別子を求めず、宛名と連絡先だけで請求先を決める。台帳に載せたい ときは顧客を作ってから `customer` を送る — Field はここから勝手に 顧客を作らない。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceBillToRequestOneOf2 {
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "phone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone: Option<Option<String>>,
}

impl InvoiceBillToRequestOneOf2 {
    /// 顧客台帳にも取引先にも無い相手への単発請求。  識別子を求めず、宛名と連絡先だけで請求先を決める。台帳に載せたい ときは顧客を作ってから `customer` を送る — Field はここから勝手に 顧客を作らない。
    pub fn new(kind: Kind, name: String) -> InvoiceBillToRequestOneOf2 {
        InvoiceBillToRequestOneOf2 {
            email: None,
            kind,
            name,
            phone: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "unregistered")]
    Unregistered,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Unregistered
    }
}
