/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceSourceResponse {
    #[serde(rename = "reason", deserialize_with = "Option::deserialize")]
    pub reason: Option<String>,
    #[serde(rename = "sourceId")]
    pub source_id: String,
    #[serde(rename = "sourceType")]
    pub source_type: String,
}

impl InvoiceSourceResponse {
    pub fn new(
        reason: Option<String>,
        source_id: String,
        source_type: String,
    ) -> InvoiceSourceResponse {
        InvoiceSourceResponse {
            reason,
            source_id,
            source_type,
        }
    }
}
