/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceBillToEvidenceResponseDirect {
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Kind>,
}

impl InvoiceBillToEvidenceResponseDirect {
    pub fn new() -> InvoiceBillToEvidenceResponseDirect {
        InvoiceBillToEvidenceResponseDirect { kind: None }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "direct")]
    Direct,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Direct
    }
}
