/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum InvoiceBillToEvidenceResponse {
    #[serde(rename = "reservation_affiliation")]
    ReservationAffiliation(Box<models::InvoiceBillToEvidenceResponseReservationAffiliation>),
    #[serde(rename = "direct")]
    Direct(Box<models::InvoiceBillToEvidenceResponseDirect>),
    /// A `kind` this client was not generated from.
    ///
    /// tachyonfield adds union variants as an additive change (CERP-25), so a
    /// tag this SDK predates is kept as the raw object instead of failing the
    /// deserialization of everything that contains it. The payload — `kind`
    /// included — is intact, and re-serializing emits it unchanged.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

impl Default for InvoiceBillToEvidenceResponse {
    fn default() -> Self {
        Self::ReservationAffiliation(Default::default())
    }
}
