/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceLineItemResponse {
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "quantity")]
    pub quantity: i64,
    #[serde(rename = "taxCategory")]
    pub tax_category: String,
    #[serde(rename = "unitPrice")]
    pub unit_price: i64,
}

impl InvoiceLineItemResponse {
    pub fn new(
        amount: i64,
        description: String,
        quantity: i64,
        tax_category: String,
        unit_price: i64,
    ) -> InvoiceLineItemResponse {
        InvoiceLineItemResponse {
            amount,
            description,
            quantity,
            tax_category,
            unit_price,
        }
    }
}
