/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InvoiceBillToRequest {
    InvoiceBillToRequestOneOf(Box<models::InvoiceBillToRequestOneOf>),
    InvoiceBillToRequestOneOf1(Box<models::InvoiceBillToRequestOneOf1>),
}

impl Default for InvoiceBillToRequest {
    fn default() -> Self {
        Self::InvoiceBillToRequestOneOf(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "client")]
    Client,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Client
    }
}
