/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileUser {
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "onboardingCompleted",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub onboarding_completed: Option<Option<bool>>,
    #[serde(
        rename = "sub",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sub: Option<Option<String>>,
    #[serde(rename = "username")]
    pub username: String,
}

impl ProfileUser {
    pub fn new(id: String, username: String) -> ProfileUser {
        ProfileUser {
            email: None,
            id,
            onboarding_completed: None,
            sub: None,
            username,
        }
    }
}
