/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicCartItemResponse {
    /// The product's own price, before the variant and option adjustments.
    #[serde(rename = "base_unit_price_nanodollar")]
    pub base_unit_price_nanodollar: i64,
    #[serde(rename = "id")]
    pub id: String,
    /// Free-text note for this line, e.g. a kitchen instruction.
    #[serde(
        rename = "note",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub note: Option<Option<String>>,
    #[serde(rename = "options")]
    pub options: Vec<models::PublicSelectedOptionResponse>,
    /// Per-unit sum of the chosen options.
    #[serde(rename = "options_total_nanodollar")]
    pub options_total_nanodollar: i64,
    #[serde(rename = "product_id")]
    pub product_id: String,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "subtotal_nanodollar")]
    pub subtotal_nanodollar: i64,
    /// Effective price per unit: base + variant + options, all resolved from the catalog. The request never states what a choice costs.
    #[serde(rename = "unit_price_nanodollar")]
    pub unit_price_nanodollar: i64,
    #[serde(
        rename = "variant_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub variant_id: Option<Option<String>>,
    #[serde(
        rename = "variant_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub variant_name: Option<Option<String>>,
    #[serde(rename = "variant_price_delta_nanodollar")]
    pub variant_price_delta_nanodollar: i64,
}

impl PublicCartItemResponse {
    pub fn new(
        base_unit_price_nanodollar: i64,
        id: String,
        options: Vec<models::PublicSelectedOptionResponse>,
        options_total_nanodollar: i64,
        product_id: String,
        quantity: i32,
        subtotal_nanodollar: i64,
        unit_price_nanodollar: i64,
        variant_price_delta_nanodollar: i64,
    ) -> PublicCartItemResponse {
        PublicCartItemResponse {
            base_unit_price_nanodollar,
            id,
            note: None,
            options,
            options_total_nanodollar,
            product_id,
            quantity,
            subtotal_nanodollar,
            unit_price_nanodollar,
            variant_id: None,
            variant_name: None,
            variant_price_delta_nanodollar,
        }
    }
}
