/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicInvoiceCheckoutResponse {
    #[serde(rename = "checkoutUrl")]
    pub checkout_url: String,
}

impl PublicInvoiceCheckoutResponse {
    pub fn new(checkout_url: String) -> PublicInvoiceCheckoutResponse {
        PublicInvoiceCheckoutResponse { checkout_url }
    }
}
