/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurgeResourceTimeSlotsResponse {
    #[serde(rename = "deleted")]
    pub deleted: i32,
    #[serde(rename = "dryRun")]
    pub dry_run: bool,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "resourceId")]
    pub resource_id: String,
    #[serde(rename = "to")]
    pub to: String,
}

impl PurgeResourceTimeSlotsResponse {
    pub fn new(
        deleted: i32,
        dry_run: bool,
        from: String,
        resource_id: String,
        to: String,
    ) -> PurgeResourceTimeSlotsResponse {
        PurgeResourceTimeSlotsResponse {
            deleted,
            dry_run,
            from,
            resource_id,
            to,
        }
    }
}
