/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistrationAddressRequest : Address written on a reception sheet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistrationAddressRequest {
    #[serde(rename = "address1")]
    pub address1: String,
    #[serde(
        rename = "address2",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub address2: Option<Option<String>>,
    #[serde(rename = "city")]
    pub city: String,
    #[serde(rename = "postalCode")]
    pub postal_code: String,
    #[serde(rename = "state")]
    pub state: String,
}

impl RegistrationAddressRequest {
    /// Address written on a reception sheet.
    pub fn new(
        address1: String,
        city: String,
        postal_code: String,
        state: String,
    ) -> RegistrationAddressRequest {
        RegistrationAddressRequest {
            address1,
            address2: None,
            city,
            postal_code,
            state,
        }
    }
}
