/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterExtensionRequest {
    #[serde(
        rename = "capabilitiesJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub capabilities_json: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "configSchemaJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config_schema_json: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "defaultConfigJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_config_json: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "deterministicOrder",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub deterministic_order: Option<Option<i32>>,
    #[serde(rename = "extensionKey")]
    pub extension_key: String,
    #[serde(rename = "industry")]
    pub industry: String,
    #[serde(rename = "manifestJson", deserialize_with = "Option::deserialize")]
    pub manifest_json: Option<serde_json::Value>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "policyHooksJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub policy_hooks_json: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "uiContributionsJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ui_contributions_json: Option<Option<serde_json::Value>>,
    #[serde(rename = "version")]
    pub version: String,
}

impl RegisterExtensionRequest {
    pub fn new(
        extension_key: String,
        industry: String,
        manifest_json: Option<serde_json::Value>,
        name: String,
        version: String,
    ) -> RegisterExtensionRequest {
        RegisterExtensionRequest {
            capabilities_json: None,
            config_schema_json: None,
            default_config_json: None,
            description: None,
            deterministic_order: None,
            extension_key,
            industry,
            manifest_json,
            name,
            policy_hooks_json: None,
            ui_contributions_json: None,
            version,
        }
    }
}
