/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistrationCustomerRequest : The customer half of a reception sheet.  Every field but the name is optional here. Which of them a given tenant actually demands is decided by its reception field settings, not by this type: a dog run asks for an address, a bar asks for nothing but a name, and the customer ledger already stores every one of these as nullable.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistrationCustomerRequest {
    #[serde(
        rename = "address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub address: Option<Option<Box<models::RegistrationAddressRequest>>>,
    /// YYYY-MM-DD
    #[serde(
        rename = "birthDate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub birth_date: Option<Option<String>>,
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "nameKana",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name_kana: Option<Option<String>>,
    #[serde(
        rename = "phone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone: Option<Option<String>>,
    /// 語彙はテナントが決める。16 文字まで。
    #[serde(
        rename = "sex",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sex: Option<Option<String>>,
}

impl RegistrationCustomerRequest {
    /// The customer half of a reception sheet.  Every field but the name is optional here. Which of them a given tenant actually demands is decided by its reception field settings, not by this type: a dog run asks for an address, a bar asks for nothing but a name, and the customer ledger already stores every one of these as nullable.
    pub fn new(name: String) -> RegistrationCustomerRequest {
        RegistrationCustomerRequest {
            address: None,
            birth_date: None,
            email: None,
            name,
            name_kana: None,
            phone: None,
            sex: None,
        }
    }
}
