/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceCaddieCourseMembershipsRequest {
    #[serde(rename = "courseIds")]
    pub course_ids: Vec<String>,
    #[serde(
        rename = "primaryCourseId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_course_id: Option<Option<String>>,
}

impl ReplaceCaddieCourseMembershipsRequest {
    pub fn new(course_ids: Vec<String>) -> ReplaceCaddieCourseMembershipsRequest {
        ReplaceCaddieCourseMembershipsRequest {
            course_ids,
            primary_course_id: None,
        }
    }
}
