/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReturnOrderRefResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: String,
}

impl ReturnOrderRefResponse {
    pub fn new(id: String, kind: String) -> ReturnOrderRefResponse {
        ReturnOrderRefResponse { id, kind }
    }
}
