/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaasChangeRequestResponse {
    #[serde(rename = "approver")]
    pub approver: String,
    #[serde(rename = "changeType")]
    pub change_type: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(
        rename = "decidedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub decided_at: Option<Option<String>>,
    #[serde(
        rename = "decidedBy",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub decided_by: Option<Option<String>>,
    #[serde(
        rename = "decisionNote",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_note: Option<Option<String>>,
    #[serde(rename = "estimatedDeltaYen")]
    pub estimated_delta_yen: i64,
    #[serde(
        rename = "fromPlan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_plan: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "requestedAt")]
    pub requested_at: String,
    #[serde(
        rename = "requestedSeats",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_seats: Option<Option<i32>>,
    #[serde(rename = "requester")]
    pub requester: String,
    #[serde(rename = "serviceName")]
    pub service_name: String,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(
        rename = "subscriptionId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subscription_id: Option<Option<String>>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(
        rename = "toPlan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub to_plan: Option<Option<String>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl SaasChangeRequestResponse {
    pub fn new(
        approver: String,
        change_type: String,
        created_at: String,
        estimated_delta_yen: i64,
        id: String,
        reason: String,
        requested_at: String,
        requester: String,
        service_name: String,
        state: String,
        tenant_id: String,
        updated_at: String,
    ) -> SaasChangeRequestResponse {
        SaasChangeRequestResponse {
            approver,
            change_type,
            created_at,
            decided_at: None,
            decided_by: None,
            decision_note: None,
            estimated_delta_yen,
            from_plan: None,
            id,
            reason,
            requested_at,
            requested_seats: None,
            requester,
            service_name,
            state,
            subscription_id: None,
            tenant_id,
            to_plan: None,
            updated_at,
        }
    }
}
