/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleDateOverrideWindow {
    /// Count of reservation groups used by schedule capacity and slot counters.  This is intentionally distinct from reservation party size, which counts people or subjects.
    #[serde(rename = "capacity")]
    pub capacity: i32,
    #[serde(rename = "endTime")]
    pub end_time: String,
    #[serde(rename = "slotIntervalMinutes")]
    pub slot_interval_minutes: i32,
    #[serde(rename = "startTime")]
    pub start_time: String,
}

impl ScheduleDateOverrideWindow {
    pub fn new(
        capacity: i32,
        end_time: String,
        slot_interval_minutes: i32,
        start_time: String,
    ) -> ScheduleDateOverrideWindow {
        ScheduleDateOverrideWindow {
            capacity,
            end_time,
            slot_interval_minutes,
            start_time,
        }
    }
}
