/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScheduleDateOverrideKind {
    #[serde(rename = "closed")]
    Closed,
    #[serde(rename = "replace")]
    Replace,
}

impl std::fmt::Display for ScheduleDateOverrideKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Closed => write!(f, "closed"),
            Self::Replace => write!(f, "replace"),
        }
    }
}

impl Default for ScheduleDateOverrideKind {
    fn default() -> ScheduleDateOverrideKind {
        Self::Closed
    }
}
