/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SquarePaymentReconciliationResponse {
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "matchReason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub match_reason: Option<Option<String>>,
    #[serde(
        rename = "matchedInvoiceId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub matched_invoice_id: Option<Option<String>>,
    #[serde(
        rename = "payerHint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub payer_hint: Option<Option<String>>,
    #[serde(
        rename = "receiptEmailSentAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub receipt_email_sent_at: Option<Option<String>>,
    #[serde(rename = "receivedAt")]
    pub received_at: String,
    #[serde(
        rename = "squareEventId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub square_event_id: Option<Option<String>>,
    #[serde(rename = "squarePaymentId")]
    pub square_payment_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl SquarePaymentReconciliationResponse {
    pub fn new(
        amount: i64,
        created_at: String,
        currency: String,
        id: String,
        received_at: String,
        square_payment_id: String,
        status: String,
        tenant_id: String,
        updated_at: String,
    ) -> SquarePaymentReconciliationResponse {
        SquarePaymentReconciliationResponse {
            amount,
            created_at,
            currency,
            id,
            match_reason: None,
            matched_invoice_id: None,
            payer_hint: None,
            receipt_email_sent_at: None,
            received_at,
            square_event_id: None,
            square_payment_id,
            status,
            tenant_id,
            updated_at,
        }
    }
}
