/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StaffAvailabilityView {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "available")]
    pub available: bool,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(
        rename = "overlappingAssignmentId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub overlapping_assignment_id: Option<Option<String>>,
    #[serde(
        rename = "overlappingReservationId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub overlapping_reservation_id: Option<Option<String>>,
    #[serde(
        rename = "profileCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_code: Option<Option<String>>,
    #[serde(
        rename = "shiftEndTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub shift_end_time: Option<Option<String>>,
    #[serde(
        rename = "shiftId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub shift_id: Option<Option<String>>,
    #[serde(
        rename = "shiftStartTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub shift_start_time: Option<Option<String>>,
    #[serde(
        rename = "staffId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub staff_id: Option<Option<String>>,
    #[serde(rename = "staffProfileId")]
    pub staff_profile_id: String,
    #[serde(rename = "unavailableReasons")]
    pub unavailable_reasons: Vec<models::GolfCaddieUnavailableReason>,
}

impl StaffAvailabilityView {
    pub fn new(
        active: bool,
        available: bool,
        display_name: String,
        staff_profile_id: String,
        unavailable_reasons: Vec<models::GolfCaddieUnavailableReason>,
    ) -> StaffAvailabilityView {
        StaffAvailabilityView {
            active,
            available,
            display_name,
            overlapping_assignment_id: None,
            overlapping_reservation_id: None,
            profile_code: None,
            shift_end_time: None,
            shift_id: None,
            shift_start_time: None,
            staff_id: None,
            staff_profile_id,
            unavailable_reasons,
        }
    }
}
