/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StaffShiftPreference {
    #[serde(rename = "availableLocations")]
    pub available_locations: Vec<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(
        rename = "desiredWorkDaysPerWeek",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub desired_work_days_per_week: Option<Option<i32>>,
    #[serde(
        rename = "monthlyIncomeTargetYen",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub monthly_income_target_yen: Option<Option<i64>>,
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(rename = "preferredDays")]
    pub preferred_days: Vec<String>,
    #[serde(rename = "preferredTimeBand")]
    pub preferred_time_band: models::StaffPreferredTimeBand,
    #[serde(rename = "staffId")]
    pub staff_id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "unavailableDates")]
    pub unavailable_dates: Vec<String>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl StaffShiftPreference {
    pub fn new(
        available_locations: Vec<String>,
        created_at: String,
        preferred_days: Vec<String>,
        preferred_time_band: models::StaffPreferredTimeBand,
        staff_id: String,
        tenant_id: String,
        unavailable_dates: Vec<String>,
        updated_at: String,
    ) -> StaffShiftPreference {
        StaffShiftPreference {
            available_locations,
            created_at,
            desired_work_days_per_week: None,
            monthly_income_target_yen: None,
            notes: None,
            preferred_days,
            preferred_time_band,
            staff_id,
            tenant_id,
            unavailable_dates,
            updated_at,
        }
    }
}
