/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StripeConnectOnboardingLinkResponse {
    #[serde(rename = "url")]
    pub url: String,
}

impl StripeConnectOnboardingLinkResponse {
    pub fn new(url: String) -> StripeConnectOnboardingLinkResponse {
        StripeConnectOnboardingLinkResponse { url }
    }
}
