/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBillingAccountRequest {
    /// Updated name for the billing account.
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateBillingAccountRequest {
    pub fn new(name: String) -> UpdateBillingAccountRequest {
        UpdateBillingAccountRequest { name }
    }
}
