/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateCouponRequest {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(
        rename = "subtotal_nanodollar",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subtotal_nanodollar: Option<Option<i64>>,
}

impl ValidateCouponRequest {
    pub fn new(code: String) -> ValidateCouponRequest {
        ValidateCouponRequest {
            code,
            subtotal_nanodollar: None,
        }
    }
}
