/*
 * tachyon-field-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoidInvoiceResponse {
    #[serde(rename = "correctionId")]
    pub correction_id: String,
    #[serde(rename = "invoice")]
    pub invoice: Box<models::InvoiceResponse>,
    #[serde(rename = "replayed")]
    pub replayed: bool,
    #[serde(rename = "reversalOn", deserialize_with = "Option::deserialize")]
    pub reversal_on: Option<String>,
    #[serde(rename = "reversedJournalCount")]
    pub reversed_journal_count: i32,
}

impl VoidInvoiceResponse {
    pub fn new(
        correction_id: String,
        invoice: models::InvoiceResponse,
        replayed: bool,
        reversal_on: Option<String>,
        reversed_journal_count: i32,
    ) -> VoidInvoiceResponse {
        VoidInvoiceResponse {
            correction_id,
            invoice: Box::new(invoice),
            replayed,
            reversal_on,
            reversed_journal_count,
        }
    }
}
