/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssignMembershipPlanRequest,
  CreateCustomerCredentialRequest,
  CreateCustomerSubjectRequest,
  CreateMembershipConsentItemRequest,
  CreateMembershipPlanRequest,
  CustomerCredentialResponse,
  CustomerSubjectResponse,
  MembershipConsentItemListResponse,
  MembershipConsentItemResponse,
  MembershipCustomerViewResponse,
  MembershipPlanAssignmentResponse,
  MembershipPlanListResponse,
  MembershipPlanResponse,
  RecordCustomerConsentsRequest,
  RegisterMembershipRequest,
  UpdateCustomerCredentialRequest,
  UpdateCustomerSubjectRequest,
  UpdateMembershipConsentItemRequest,
  UpdateMembershipPlanRequest,
} from '../models/index';

export interface ArchiveCustomerSubjectRequest {
    id: string;
}

export interface AssignMembershipPlanOperationRequest {
    customerId: string;
    assignMembershipPlanRequest: AssignMembershipPlanRequest;
}

export interface CreateCustomerCredentialOperationRequest {
    customerId: string;
    createCustomerCredentialRequest: CreateCustomerCredentialRequest;
}

export interface CreateCustomerSubjectOperationRequest {
    customerId: string;
    createCustomerSubjectRequest: CreateCustomerSubjectRequest;
}

export interface CreateMembershipConsentItemOperationRequest {
    createMembershipConsentItemRequest: CreateMembershipConsentItemRequest;
}

export interface CreateMembershipPlanOperationRequest {
    createMembershipPlanRequest: CreateMembershipPlanRequest;
}

export interface DeleteMembershipConsentItemRequest {
    id: string;
}

export interface DeleteMembershipPlanRequest {
    id: string;
}

export interface GetCustomerMembershipRequest {
    customerId: string;
}

export interface ListMembershipConsentItemsRequest {
    includeInactive?: boolean | null;
}

export interface ListMembershipPlansRequest {
    includeInactive?: boolean | null;
}

export interface RecordCustomerConsentsOperationRequest {
    customerId: string;
    recordCustomerConsentsRequest: RecordCustomerConsentsRequest;
}

export interface RegisterMembershipOperationRequest {
    registerMembershipRequest: RegisterMembershipRequest;
}

export interface UpdateCustomerCredentialOperationRequest {
    id: string;
    updateCustomerCredentialRequest: UpdateCustomerCredentialRequest;
}

export interface UpdateCustomerSubjectOperationRequest {
    id: string;
    updateCustomerSubjectRequest: UpdateCustomerSubjectRequest;
}

export interface UpdateMembershipConsentItemOperationRequest {
    id: string;
    updateMembershipConsentItemRequest: UpdateMembershipConsentItemRequest;
}

export interface UpdateMembershipPlanOperationRequest {
    id: string;
    updateMembershipPlanRequest: UpdateMembershipPlanRequest;
}

/**
 * 
 */
export class MembershipApi extends runtime.BaseAPI {

    /**
     * Creates request options for archiveCustomerSubject without sending the request
     */
    async archiveCustomerSubjectRequestOpts(requestParameters: ArchiveCustomerSubjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling archiveCustomerSubject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/subjects/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async archiveCustomerSubjectRaw(requestParameters: ArchiveCustomerSubjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.archiveCustomerSubjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async archiveCustomerSubject(requestParameters: ArchiveCustomerSubjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.archiveCustomerSubjectRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for assignMembershipPlan without sending the request
     */
    async assignMembershipPlanRequestOpts(requestParameters: AssignMembershipPlanOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling assignMembershipPlan().'
            );
        }

        if (requestParameters['assignMembershipPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'assignMembershipPlanRequest',
                'Required parameter "assignMembershipPlanRequest" was null or undefined when calling assignMembershipPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/customers/{customer_id}/plan-assignments`;
        urlPath = urlPath.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['assignMembershipPlanRequest'],
        };
    }

    /**
     */
    async assignMembershipPlanRaw(requestParameters: AssignMembershipPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipPlanAssignmentResponse>> {
        const requestOptions = await this.assignMembershipPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async assignMembershipPlan(requestParameters: AssignMembershipPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipPlanAssignmentResponse> {
        const response = await this.assignMembershipPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCustomerCredential without sending the request
     */
    async createCustomerCredentialRequestOpts(requestParameters: CreateCustomerCredentialOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling createCustomerCredential().'
            );
        }

        if (requestParameters['createCustomerCredentialRequest'] == null) {
            throw new runtime.RequiredError(
                'createCustomerCredentialRequest',
                'Required parameter "createCustomerCredentialRequest" was null or undefined when calling createCustomerCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/customers/{customer_id}/credentials`;
        urlPath = urlPath.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createCustomerCredentialRequest'],
        };
    }

    /**
     */
    async createCustomerCredentialRaw(requestParameters: CreateCustomerCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCredentialResponse>> {
        const requestOptions = await this.createCustomerCredentialRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createCustomerCredential(requestParameters: CreateCustomerCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCredentialResponse> {
        const response = await this.createCustomerCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCustomerSubject without sending the request
     */
    async createCustomerSubjectRequestOpts(requestParameters: CreateCustomerSubjectOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling createCustomerSubject().'
            );
        }

        if (requestParameters['createCustomerSubjectRequest'] == null) {
            throw new runtime.RequiredError(
                'createCustomerSubjectRequest',
                'Required parameter "createCustomerSubjectRequest" was null or undefined when calling createCustomerSubject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/customers/{customer_id}/subjects`;
        urlPath = urlPath.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createCustomerSubjectRequest'],
        };
    }

    /**
     */
    async createCustomerSubjectRaw(requestParameters: CreateCustomerSubjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSubjectResponse>> {
        const requestOptions = await this.createCustomerSubjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createCustomerSubject(requestParameters: CreateCustomerSubjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSubjectResponse> {
        const response = await this.createCustomerSubjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createMembershipConsentItem without sending the request
     */
    async createMembershipConsentItemRequestOpts(requestParameters: CreateMembershipConsentItemOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createMembershipConsentItemRequest'] == null) {
            throw new runtime.RequiredError(
                'createMembershipConsentItemRequest',
                'Required parameter "createMembershipConsentItemRequest" was null or undefined when calling createMembershipConsentItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/consent-items`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createMembershipConsentItemRequest'],
        };
    }

    /**
     */
    async createMembershipConsentItemRaw(requestParameters: CreateMembershipConsentItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipConsentItemResponse>> {
        const requestOptions = await this.createMembershipConsentItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createMembershipConsentItem(requestParameters: CreateMembershipConsentItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipConsentItemResponse> {
        const response = await this.createMembershipConsentItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createMembershipPlan without sending the request
     */
    async createMembershipPlanRequestOpts(requestParameters: CreateMembershipPlanOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createMembershipPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'createMembershipPlanRequest',
                'Required parameter "createMembershipPlanRequest" was null or undefined when calling createMembershipPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/plans`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createMembershipPlanRequest'],
        };
    }

    /**
     */
    async createMembershipPlanRaw(requestParameters: CreateMembershipPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipPlanResponse>> {
        const requestOptions = await this.createMembershipPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createMembershipPlan(requestParameters: CreateMembershipPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipPlanResponse> {
        const response = await this.createMembershipPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteMembershipConsentItem without sending the request
     */
    async deleteMembershipConsentItemRequestOpts(requestParameters: DeleteMembershipConsentItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteMembershipConsentItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/consent-items/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteMembershipConsentItemRaw(requestParameters: DeleteMembershipConsentItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMembershipConsentItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteMembershipConsentItem(requestParameters: DeleteMembershipConsentItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMembershipConsentItemRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteMembershipPlan without sending the request
     */
    async deleteMembershipPlanRequestOpts(requestParameters: DeleteMembershipPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteMembershipPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteMembershipPlanRaw(requestParameters: DeleteMembershipPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMembershipPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteMembershipPlan(requestParameters: DeleteMembershipPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMembershipPlanRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCustomerMembership without sending the request
     */
    async getCustomerMembershipRequestOpts(requestParameters: GetCustomerMembershipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling getCustomerMembership().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/customers/{customer_id}`;
        urlPath = urlPath.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCustomerMembershipRaw(requestParameters: GetCustomerMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipCustomerViewResponse>> {
        const requestOptions = await this.getCustomerMembershipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getCustomerMembership(requestParameters: GetCustomerMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipCustomerViewResponse> {
        const response = await this.getCustomerMembershipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMembershipConsentItems without sending the request
     */
    async listMembershipConsentItemsRequestOpts(requestParameters: ListMembershipConsentItemsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['includeInactive'] != null) {
            queryParameters['includeInactive'] = requestParameters['includeInactive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/consent-items`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listMembershipConsentItemsRaw(requestParameters: ListMembershipConsentItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipConsentItemListResponse>> {
        const requestOptions = await this.listMembershipConsentItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async listMembershipConsentItems(requestParameters: ListMembershipConsentItemsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipConsentItemListResponse> {
        const response = await this.listMembershipConsentItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMembershipPlans without sending the request
     */
    async listMembershipPlansRequestOpts(requestParameters: ListMembershipPlansRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['includeInactive'] != null) {
            queryParameters['includeInactive'] = requestParameters['includeInactive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/plans`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listMembershipPlansRaw(requestParameters: ListMembershipPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipPlanListResponse>> {
        const requestOptions = await this.listMembershipPlansRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async listMembershipPlans(requestParameters: ListMembershipPlansRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipPlanListResponse> {
        const response = await this.listMembershipPlansRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recordCustomerConsents without sending the request
     */
    async recordCustomerConsentsRequestOpts(requestParameters: RecordCustomerConsentsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling recordCustomerConsents().'
            );
        }

        if (requestParameters['recordCustomerConsentsRequest'] == null) {
            throw new runtime.RequiredError(
                'recordCustomerConsentsRequest',
                'Required parameter "recordCustomerConsentsRequest" was null or undefined when calling recordCustomerConsents().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/customers/{customer_id}/consents`;
        urlPath = urlPath.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['recordCustomerConsentsRequest'],
        };
    }

    /**
     */
    async recordCustomerConsentsRaw(requestParameters: RecordCustomerConsentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipCustomerViewResponse>> {
        const requestOptions = await this.recordCustomerConsentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async recordCustomerConsents(requestParameters: RecordCustomerConsentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipCustomerViewResponse> {
        const response = await this.recordCustomerConsentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerMembership without sending the request
     */
    async registerMembershipRequestOpts(requestParameters: RegisterMembershipOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerMembershipRequest'] == null) {
            throw new runtime.RequiredError(
                'registerMembershipRequest',
                'Required parameter "registerMembershipRequest" was null or undefined when calling registerMembership().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/registrations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['registerMembershipRequest'],
        };
    }

    /**
     */
    async registerMembershipRaw(requestParameters: RegisterMembershipOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipCustomerViewResponse>> {
        const requestOptions = await this.registerMembershipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async registerMembership(requestParameters: RegisterMembershipOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipCustomerViewResponse> {
        const response = await this.registerMembershipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCustomerCredential without sending the request
     */
    async updateCustomerCredentialRequestOpts(requestParameters: UpdateCustomerCredentialOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCustomerCredential().'
            );
        }

        if (requestParameters['updateCustomerCredentialRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCustomerCredentialRequest',
                'Required parameter "updateCustomerCredentialRequest" was null or undefined when calling updateCustomerCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/credentials/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateCustomerCredentialRequest'],
        };
    }

    /**
     */
    async updateCustomerCredentialRaw(requestParameters: UpdateCustomerCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCredentialResponse>> {
        const requestOptions = await this.updateCustomerCredentialRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async updateCustomerCredential(requestParameters: UpdateCustomerCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCredentialResponse> {
        const response = await this.updateCustomerCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCustomerSubject without sending the request
     */
    async updateCustomerSubjectRequestOpts(requestParameters: UpdateCustomerSubjectOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCustomerSubject().'
            );
        }

        if (requestParameters['updateCustomerSubjectRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCustomerSubjectRequest',
                'Required parameter "updateCustomerSubjectRequest" was null or undefined when calling updateCustomerSubject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/subjects/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateCustomerSubjectRequest'],
        };
    }

    /**
     */
    async updateCustomerSubjectRaw(requestParameters: UpdateCustomerSubjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSubjectResponse>> {
        const requestOptions = await this.updateCustomerSubjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async updateCustomerSubject(requestParameters: UpdateCustomerSubjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSubjectResponse> {
        const response = await this.updateCustomerSubjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateMembershipConsentItem without sending the request
     */
    async updateMembershipConsentItemRequestOpts(requestParameters: UpdateMembershipConsentItemOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateMembershipConsentItem().'
            );
        }

        if (requestParameters['updateMembershipConsentItemRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMembershipConsentItemRequest',
                'Required parameter "updateMembershipConsentItemRequest" was null or undefined when calling updateMembershipConsentItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/consent-items/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateMembershipConsentItemRequest'],
        };
    }

    /**
     */
    async updateMembershipConsentItemRaw(requestParameters: UpdateMembershipConsentItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipConsentItemResponse>> {
        const requestOptions = await this.updateMembershipConsentItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async updateMembershipConsentItem(requestParameters: UpdateMembershipConsentItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipConsentItemResponse> {
        const response = await this.updateMembershipConsentItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateMembershipPlan without sending the request
     */
    async updateMembershipPlanRequestOpts(requestParameters: UpdateMembershipPlanOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateMembershipPlan().'
            );
        }

        if (requestParameters['updateMembershipPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMembershipPlanRequest',
                'Required parameter "updateMembershipPlanRequest" was null or undefined when calling updateMembershipPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/membership/plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateMembershipPlanRequest'],
        };
    }

    /**
     */
    async updateMembershipPlanRaw(requestParameters: UpdateMembershipPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipPlanResponse>> {
        const requestOptions = await this.updateMembershipPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async updateMembershipPlan(requestParameters: UpdateMembershipPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipPlanResponse> {
        const response = await this.updateMembershipPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
