/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicInvoiceCheckoutResponse,
  PublicInvoicePaymentConfirmationRequest,
  PublicInvoicePaymentConfirmationResponse,
  PublicInvoicePaymentIntentResponse,
  PublicInvoiceResponse,
  PublicInvoiceStripePublishableKeyResponse,
} from '../models/index';

export interface ConfirmPublicInvoicePaymentRequest {
    tenantId: string;
    id: string;
    publicInvoicePaymentConfirmationRequest: PublicInvoicePaymentConfirmationRequest;
}

export interface ConfirmShortPublicInvoicePaymentRequest {
    id: string;
    publicInvoicePaymentConfirmationRequest: PublicInvoicePaymentConfirmationRequest;
}

export interface CreatePublicInvoiceCheckoutRequest {
    tenantId: string;
    id: string;
}

export interface CreatePublicInvoicePaymentIntentRequest {
    tenantId: string;
    id: string;
    apiKey?: string | null;
    publicApiKey?: string | null;
}

export interface CreateShortPublicInvoiceCheckoutRequest {
    id: string;
}

export interface CreateShortPublicInvoicePaymentIntentRequest {
    id: string;
    apiKey?: string | null;
    publicApiKey?: string | null;
}

export interface GetPublicInvoiceRequest {
    tenantId: string;
    id: string;
}

export interface GetPublicInvoiceStripePublishableKeyRequest {
    tenantId: string;
    id: string;
    apiKey?: string | null;
    publicApiKey?: string | null;
}

export interface GetShortPublicInvoiceRequest {
    id: string;
}

export interface GetShortPublicInvoiceStripePublishableKeyRequest {
    id: string;
    apiKey?: string | null;
    publicApiKey?: string | null;
}

/**
 * 
 */
export class PublicInvoicesApi extends runtime.BaseAPI {

    /**
     * Creates request options for confirmPublicInvoicePayment without sending the request
     */
    async confirmPublicInvoicePaymentRequestOpts(requestParameters: ConfirmPublicInvoicePaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling confirmPublicInvoicePayment().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling confirmPublicInvoicePayment().'
            );
        }

        if (requestParameters['publicInvoicePaymentConfirmationRequest'] == null) {
            throw new runtime.RequiredError(
                'publicInvoicePaymentConfirmationRequest',
                'Required parameter "publicInvoicePaymentConfirmationRequest" was null or undefined when calling confirmPublicInvoicePayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{tenant_id}/{id}/payment-confirmation`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['publicInvoicePaymentConfirmationRequest'],
        };
    }

    /**
     */
    async confirmPublicInvoicePaymentRaw(requestParameters: ConfirmPublicInvoicePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoicePaymentConfirmationResponse>> {
        const requestOptions = await this.confirmPublicInvoicePaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async confirmPublicInvoicePayment(requestParameters: ConfirmPublicInvoicePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoicePaymentConfirmationResponse> {
        const response = await this.confirmPublicInvoicePaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for confirmShortPublicInvoicePayment without sending the request
     */
    async confirmShortPublicInvoicePaymentRequestOpts(requestParameters: ConfirmShortPublicInvoicePaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling confirmShortPublicInvoicePayment().'
            );
        }

        if (requestParameters['publicInvoicePaymentConfirmationRequest'] == null) {
            throw new runtime.RequiredError(
                'publicInvoicePaymentConfirmationRequest',
                'Required parameter "publicInvoicePaymentConfirmationRequest" was null or undefined when calling confirmShortPublicInvoicePayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{id}/payment-confirmation`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['publicInvoicePaymentConfirmationRequest'],
        };
    }

    /**
     */
    async confirmShortPublicInvoicePaymentRaw(requestParameters: ConfirmShortPublicInvoicePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoicePaymentConfirmationResponse>> {
        const requestOptions = await this.confirmShortPublicInvoicePaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async confirmShortPublicInvoicePayment(requestParameters: ConfirmShortPublicInvoicePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoicePaymentConfirmationResponse> {
        const response = await this.confirmShortPublicInvoicePaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPublicInvoiceCheckout without sending the request
     */
    async createPublicInvoiceCheckoutRequestOpts(requestParameters: CreatePublicInvoiceCheckoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling createPublicInvoiceCheckout().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPublicInvoiceCheckout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{tenant_id}/{id}/checkout`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createPublicInvoiceCheckoutRaw(requestParameters: CreatePublicInvoiceCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoiceCheckoutResponse>> {
        const requestOptions = await this.createPublicInvoiceCheckoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createPublicInvoiceCheckout(requestParameters: CreatePublicInvoiceCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoiceCheckoutResponse> {
        const response = await this.createPublicInvoiceCheckoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPublicInvoicePaymentIntent without sending the request
     */
    async createPublicInvoicePaymentIntentRequestOpts(requestParameters: CreatePublicInvoicePaymentIntentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling createPublicInvoicePaymentIntent().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPublicInvoicePaymentIntent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiKey'] != null) {
            queryParameters['apiKey'] = requestParameters['apiKey'];
        }

        if (requestParameters['publicApiKey'] != null) {
            queryParameters['publicApiKey'] = requestParameters['publicApiKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{tenant_id}/{id}/payment-intent`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createPublicInvoicePaymentIntentRaw(requestParameters: CreatePublicInvoicePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoicePaymentIntentResponse>> {
        const requestOptions = await this.createPublicInvoicePaymentIntentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createPublicInvoicePaymentIntent(requestParameters: CreatePublicInvoicePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoicePaymentIntentResponse> {
        const response = await this.createPublicInvoicePaymentIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createShortPublicInvoiceCheckout without sending the request
     */
    async createShortPublicInvoiceCheckoutRequestOpts(requestParameters: CreateShortPublicInvoiceCheckoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createShortPublicInvoiceCheckout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{id}/checkout`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createShortPublicInvoiceCheckoutRaw(requestParameters: CreateShortPublicInvoiceCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoiceCheckoutResponse>> {
        const requestOptions = await this.createShortPublicInvoiceCheckoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createShortPublicInvoiceCheckout(requestParameters: CreateShortPublicInvoiceCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoiceCheckoutResponse> {
        const response = await this.createShortPublicInvoiceCheckoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createShortPublicInvoicePaymentIntent without sending the request
     */
    async createShortPublicInvoicePaymentIntentRequestOpts(requestParameters: CreateShortPublicInvoicePaymentIntentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createShortPublicInvoicePaymentIntent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiKey'] != null) {
            queryParameters['apiKey'] = requestParameters['apiKey'];
        }

        if (requestParameters['publicApiKey'] != null) {
            queryParameters['publicApiKey'] = requestParameters['publicApiKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{id}/payment-intent`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createShortPublicInvoicePaymentIntentRaw(requestParameters: CreateShortPublicInvoicePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoicePaymentIntentResponse>> {
        const requestOptions = await this.createShortPublicInvoicePaymentIntentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createShortPublicInvoicePaymentIntent(requestParameters: CreateShortPublicInvoicePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoicePaymentIntentResponse> {
        const response = await this.createShortPublicInvoicePaymentIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPublicInvoice without sending the request
     */
    async getPublicInvoiceRequestOpts(requestParameters: GetPublicInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling getPublicInvoice().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPublicInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{tenant_id}/{id}`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPublicInvoiceRaw(requestParameters: GetPublicInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoiceResponse>> {
        const requestOptions = await this.getPublicInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getPublicInvoice(requestParameters: GetPublicInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoiceResponse> {
        const response = await this.getPublicInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPublicInvoiceStripePublishableKey without sending the request
     */
    async getPublicInvoiceStripePublishableKeyRequestOpts(requestParameters: GetPublicInvoiceStripePublishableKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling getPublicInvoiceStripePublishableKey().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPublicInvoiceStripePublishableKey().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiKey'] != null) {
            queryParameters['apiKey'] = requestParameters['apiKey'];
        }

        if (requestParameters['publicApiKey'] != null) {
            queryParameters['publicApiKey'] = requestParameters['publicApiKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{tenant_id}/{id}/stripe-publishable-key`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPublicInvoiceStripePublishableKeyRaw(requestParameters: GetPublicInvoiceStripePublishableKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoiceStripePublishableKeyResponse>> {
        const requestOptions = await this.getPublicInvoiceStripePublishableKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getPublicInvoiceStripePublishableKey(requestParameters: GetPublicInvoiceStripePublishableKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoiceStripePublishableKeyResponse> {
        const response = await this.getPublicInvoiceStripePublishableKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getShortPublicInvoice without sending the request
     */
    async getShortPublicInvoiceRequestOpts(requestParameters: GetShortPublicInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getShortPublicInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getShortPublicInvoiceRaw(requestParameters: GetShortPublicInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoiceResponse>> {
        const requestOptions = await this.getShortPublicInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getShortPublicInvoice(requestParameters: GetShortPublicInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoiceResponse> {
        const response = await this.getShortPublicInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getShortPublicInvoiceStripePublishableKey without sending the request
     */
    async getShortPublicInvoiceStripePublishableKeyRequestOpts(requestParameters: GetShortPublicInvoiceStripePublishableKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getShortPublicInvoiceStripePublishableKey().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiKey'] != null) {
            queryParameters['apiKey'] = requestParameters['apiKey'];
        }

        if (requestParameters['publicApiKey'] != null) {
            queryParameters['publicApiKey'] = requestParameters['publicApiKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/public/invoices/{id}/stripe-publishable-key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getShortPublicInvoiceStripePublishableKeyRaw(requestParameters: GetShortPublicInvoiceStripePublishableKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInvoiceStripePublishableKeyResponse>> {
        const requestOptions = await this.getShortPublicInvoiceStripePublishableKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getShortPublicInvoiceStripePublishableKey(requestParameters: GetShortPublicInvoiceStripePublishableKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInvoiceStripePublishableKeyResponse> {
        const response = await this.getShortPublicInvoiceStripePublishableKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
