/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSaasChangeRequestRequest,
  CreateSaasSubscriptionRequest,
  DecideSaasChangeRequestRequest,
  SaasChangeRequestListResponse,
  SaasChangeRequestResponse,
  SaasSubscriptionListResponse,
  SaasSubscriptionResponse,
  UpdateSaasSubscriptionRequest,
} from '../models/index';

export interface ApproveSaasChangeRequestRequest {
    id: string;
    decideSaasChangeRequestRequest: DecideSaasChangeRequestRequest;
}

export interface CreateSaasChangeRequestOperationRequest {
    createSaasChangeRequestRequest: CreateSaasChangeRequestRequest;
    idempotencyKey?: string | null;
}

export interface CreateSaasSubscriptionOperationRequest {
    createSaasSubscriptionRequest: CreateSaasSubscriptionRequest;
}

export interface ListSaasChangeRequestsRequest {
    state?: string | null;
}

export interface ListSaasSubscriptionsRequest {
    status?: string | null;
}

export interface ReturnSaasChangeRequestRequest {
    id: string;
    decideSaasChangeRequestRequest: DecideSaasChangeRequestRequest;
}

export interface UpdateSaasSubscriptionOperationRequest {
    id: string;
    updateSaasSubscriptionRequest: UpdateSaasSubscriptionRequest;
}

/**
 * 
 */
export class SaaSSubscriptionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for approveSaasChangeRequest without sending the request
     */
    async approveSaasChangeRequestRequestOpts(requestParameters: ApproveSaasChangeRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling approveSaasChangeRequest().'
            );
        }

        if (requestParameters['decideSaasChangeRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'decideSaasChangeRequestRequest',
                'Required parameter "decideSaasChangeRequestRequest" was null or undefined when calling approveSaasChangeRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/saas-subscription-requests/{id}/approve`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['decideSaasChangeRequestRequest'],
        };
    }

    /**
     */
    async approveSaasChangeRequestRaw(requestParameters: ApproveSaasChangeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasChangeRequestResponse>> {
        const requestOptions = await this.approveSaasChangeRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async approveSaasChangeRequest(requestParameters: ApproveSaasChangeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasChangeRequestResponse> {
        const response = await this.approveSaasChangeRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSaasChangeRequest without sending the request
     */
    async createSaasChangeRequestRequestOpts(requestParameters: CreateSaasChangeRequestOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSaasChangeRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'createSaasChangeRequestRequest',
                'Required parameter "createSaasChangeRequestRequest" was null or undefined when calling createSaasChangeRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/saas-subscription-requests`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createSaasChangeRequestRequest'],
        };
    }

    /**
     */
    async createSaasChangeRequestRaw(requestParameters: CreateSaasChangeRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasChangeRequestResponse>> {
        const requestOptions = await this.createSaasChangeRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createSaasChangeRequest(requestParameters: CreateSaasChangeRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasChangeRequestResponse> {
        const response = await this.createSaasChangeRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSaasSubscription without sending the request
     */
    async createSaasSubscriptionRequestOpts(requestParameters: CreateSaasSubscriptionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSaasSubscriptionRequest'] == null) {
            throw new runtime.RequiredError(
                'createSaasSubscriptionRequest',
                'Required parameter "createSaasSubscriptionRequest" was null or undefined when calling createSaasSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/saas-subscriptions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createSaasSubscriptionRequest'],
        };
    }

    /**
     */
    async createSaasSubscriptionRaw(requestParameters: CreateSaasSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasSubscriptionResponse>> {
        const requestOptions = await this.createSaasSubscriptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createSaasSubscription(requestParameters: CreateSaasSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasSubscriptionResponse> {
        const response = await this.createSaasSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSaasChangeRequests without sending the request
     */
    async listSaasChangeRequestsRequestOpts(requestParameters: ListSaasChangeRequestsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/saas-subscription-requests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listSaasChangeRequestsRaw(requestParameters: ListSaasChangeRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasChangeRequestListResponse>> {
        const requestOptions = await this.listSaasChangeRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async listSaasChangeRequests(requestParameters: ListSaasChangeRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasChangeRequestListResponse> {
        const response = await this.listSaasChangeRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSaasSubscriptions without sending the request
     */
    async listSaasSubscriptionsRequestOpts(requestParameters: ListSaasSubscriptionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/saas-subscriptions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listSaasSubscriptionsRaw(requestParameters: ListSaasSubscriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasSubscriptionListResponse>> {
        const requestOptions = await this.listSaasSubscriptionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async listSaasSubscriptions(requestParameters: ListSaasSubscriptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasSubscriptionListResponse> {
        const response = await this.listSaasSubscriptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for returnSaasChangeRequest without sending the request
     */
    async returnSaasChangeRequestRequestOpts(requestParameters: ReturnSaasChangeRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling returnSaasChangeRequest().'
            );
        }

        if (requestParameters['decideSaasChangeRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'decideSaasChangeRequestRequest',
                'Required parameter "decideSaasChangeRequestRequest" was null or undefined when calling returnSaasChangeRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/saas-subscription-requests/{id}/return`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['decideSaasChangeRequestRequest'],
        };
    }

    /**
     */
    async returnSaasChangeRequestRaw(requestParameters: ReturnSaasChangeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasChangeRequestResponse>> {
        const requestOptions = await this.returnSaasChangeRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async returnSaasChangeRequest(requestParameters: ReturnSaasChangeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasChangeRequestResponse> {
        const response = await this.returnSaasChangeRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSaasSubscription without sending the request
     */
    async updateSaasSubscriptionRequestOpts(requestParameters: UpdateSaasSubscriptionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSaasSubscription().'
            );
        }

        if (requestParameters['updateSaasSubscriptionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSaasSubscriptionRequest',
                'Required parameter "updateSaasSubscriptionRequest" was null or undefined when calling updateSaasSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/saas-subscriptions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateSaasSubscriptionRequest'],
        };
    }

    /**
     */
    async updateSaasSubscriptionRaw(requestParameters: UpdateSaasSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasSubscriptionResponse>> {
        const requestOptions = await this.updateSaasSubscriptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async updateSaasSubscription(requestParameters: UpdateSaasSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasSubscriptionResponse> {
        const response = await this.updateSaasSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
