/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClientCsvImportResponse,
} from '../models/index';

export interface ImportClientsCsvRequest {
    body: string;
}

/**
 * 
 */
export class TACHYONFieldCRMClientsApi extends runtime.BaseAPI {

    /**
     * Creates request options for exportClientsCsv without sending the request
     */
    async exportClientsCsvRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/clients/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async exportClientsCsvRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.exportClientsCsvRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async exportClientsCsv(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.exportClientsCsvRaw(initOverrides);
    }

    /**
     * Creates request options for importClientsCsv without sending the request
     */
    async importClientsCsvRequestOpts(requestParameters: ImportClientsCsvRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling importClientsCsv().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/csv';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/clients/import.csv`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async importClientsCsvRaw(requestParameters: ImportClientsCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientCsvImportResponse>> {
        const requestOptions = await this.importClientsCsvRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async importClientsCsv(requestParameters: ImportClientsCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientCsvImportResponse> {
        const response = await this.importClientsCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
