/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateStripeConnectOnboardingLinkRequest,
  StripeConnectAccountResponse,
  StripeConnectOnboardingLinkResponse,
} from '../models/index';

export interface CreateStripeConnectOnboardingLinkOperationRequest {
    createStripeConnectOnboardingLinkRequest: CreateStripeConnectOnboardingLinkRequest;
}

/**
 * 
 */
export class TACHYONFieldStripeConnectApi extends runtime.BaseAPI {

    /**
     * Creates request options for createStripeConnectAccount without sending the request
     */
    async createStripeConnectAccountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/payments/stripe-connect/account`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createStripeConnectAccountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StripeConnectAccountResponse>> {
        const requestOptions = await this.createStripeConnectAccountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createStripeConnectAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StripeConnectAccountResponse> {
        const response = await this.createStripeConnectAccountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createStripeConnectOnboardingLink without sending the request
     */
    async createStripeConnectOnboardingLinkRequestOpts(requestParameters: CreateStripeConnectOnboardingLinkOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createStripeConnectOnboardingLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'createStripeConnectOnboardingLinkRequest',
                'Required parameter "createStripeConnectOnboardingLinkRequest" was null or undefined when calling createStripeConnectOnboardingLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/payments/stripe-connect/onboarding-link`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createStripeConnectOnboardingLinkRequest'],
        };
    }

    /**
     */
    async createStripeConnectOnboardingLinkRaw(requestParameters: CreateStripeConnectOnboardingLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StripeConnectOnboardingLinkResponse>> {
        const requestOptions = await this.createStripeConnectOnboardingLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createStripeConnectOnboardingLink(requestParameters: CreateStripeConnectOnboardingLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StripeConnectOnboardingLinkResponse> {
        const response = await this.createStripeConnectOnboardingLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStripeConnectAccount without sending the request
     */
    async getStripeConnectAccountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/erp/payments/stripe-connect/account`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getStripeConnectAccountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StripeConnectAccountResponse>> {
        const requestOptions = await this.getStripeConnectAccountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getStripeConnectAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StripeConnectAccountResponse> {
        const response = await this.getStripeConnectAccountRaw(initOverrides);
        return await response.value();
    }

}
