/* tslint:disable */
/* eslint-disable */
/**
 * tachyon-field-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BridgeActionRequest,
  BridgeActionResponse,
  BridgeDefinitionListResponse,
  BridgeDefinitionRequest,
  BridgeDefinitionResponse,
  BridgeRunListResponse,
  BridgeRunPreviewRequest,
  BridgeRunResponse,
  ErrorResponse,
  TabularAnalyzeResponse,
} from '../models/index';

export interface AnalyzeBridgeTabularRequest {
    file: Blob;
    context?: string | null;
    headerRow?: number | null;
    idempotencyKey?: string | null;
    mappingMode?: string | null;
    mappingProposal?: string | null;
    sheetName?: string | null;
    targetSchema?: string | null;
}

export interface CreateBridgeDefinitionRequest {
    bridgeDefinitionRequest: BridgeDefinitionRequest;
}

export interface ExecuteBridgeRunRequest {
    runId: string;
}

export interface GetBridgeRunRequest {
    runId: string;
}

export interface InvokeBridgeActionRequest {
    action: string;
    bridgeActionRequest: BridgeActionRequest;
}

export interface ListBridgeRunsRequest {
    limit?: number | null;
    offset?: number | null;
}

export interface PreviewBridgeFileRequest {
    definitionId: string;
    file: Blob;
    context?: string | null;
    headerRow?: number | null;
    idempotencyKey?: string | null;
    mappingMode?: string | null;
    mappingProposal?: string | null;
    sheetName?: string | null;
    targetSchema?: string | null;
}

export interface PreviewBridgeRunRequest {
    definitionId: string;
    bridgeRunPreviewRequest: BridgeRunPreviewRequest;
}

/**
 * 
 */
export class TACHYONFieldBridgeApi extends runtime.BaseAPI {

    /**
     * Creates request options for analyzeBridgeTabular without sending the request
     */
    async analyzeBridgeTabularRequestOpts(requestParameters: AnalyzeBridgeTabularRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling analyzeBridgeTabular().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['context'] != null) {
            formParams.append('context', requestParameters['context'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['headerRow'] != null) {
            formParams.append('headerRow', requestParameters['headerRow'] as any);
        }

        if (requestParameters['idempotencyKey'] != null) {
            formParams.append('idempotencyKey', requestParameters['idempotencyKey'] as any);
        }

        if (requestParameters['mappingMode'] != null) {
            formParams.append('mappingMode', requestParameters['mappingMode'] as any);
        }

        if (requestParameters['mappingProposal'] != null) {
            formParams.append('mappingProposal', requestParameters['mappingProposal'] as any);
        }

        if (requestParameters['sheetName'] != null) {
            formParams.append('sheetName', requestParameters['sheetName'] as any);
        }

        if (requestParameters['targetSchema'] != null) {
            formParams.append('targetSchema', requestParameters['targetSchema'] as any);
        }


        let urlPath = `/v1/bridge/tabular/analyze`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async analyzeBridgeTabularRaw(requestParameters: AnalyzeBridgeTabularRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TabularAnalyzeResponse>> {
        const requestOptions = await this.analyzeBridgeTabularRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async analyzeBridgeTabular(requestParameters: AnalyzeBridgeTabularRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TabularAnalyzeResponse> {
        const response = await this.analyzeBridgeTabularRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createBridgeDefinition without sending the request
     */
    async createBridgeDefinitionRequestOpts(requestParameters: CreateBridgeDefinitionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bridgeDefinitionRequest'] == null) {
            throw new runtime.RequiredError(
                'bridgeDefinitionRequest',
                'Required parameter "bridgeDefinitionRequest" was null or undefined when calling createBridgeDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/bridge/definitions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['bridgeDefinitionRequest'],
        };
    }

    /**
     */
    async createBridgeDefinitionRaw(requestParameters: CreateBridgeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeDefinitionResponse>> {
        const requestOptions = await this.createBridgeDefinitionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async createBridgeDefinition(requestParameters: CreateBridgeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeDefinitionResponse> {
        const response = await this.createBridgeDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for executeBridgeRun without sending the request
     */
    async executeBridgeRunRequestOpts(requestParameters: ExecuteBridgeRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling executeBridgeRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/bridge/runs/{run_id}/execute`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async executeBridgeRunRaw(requestParameters: ExecuteBridgeRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeRunResponse>> {
        const requestOptions = await this.executeBridgeRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async executeBridgeRun(requestParameters: ExecuteBridgeRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeRunResponse> {
        const response = await this.executeBridgeRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBridgeRun without sending the request
     */
    async getBridgeRunRequestOpts(requestParameters: GetBridgeRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getBridgeRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/bridge/runs/{run_id}`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getBridgeRunRaw(requestParameters: GetBridgeRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeRunResponse>> {
        const requestOptions = await this.getBridgeRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getBridgeRun(requestParameters: GetBridgeRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeRunResponse> {
        const response = await this.getBridgeRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for invokeBridgeAction without sending the request
     */
    async invokeBridgeActionRequestOpts(requestParameters: InvokeBridgeActionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling invokeBridgeAction().'
            );
        }

        if (requestParameters['bridgeActionRequest'] == null) {
            throw new runtime.RequiredError(
                'bridgeActionRequest',
                'Required parameter "bridgeActionRequest" was null or undefined when calling invokeBridgeAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/bridge/actions/{action}`;
        urlPath = urlPath.replace(`{${"action"}}`, encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['bridgeActionRequest'],
        };
    }

    /**
     */
    async invokeBridgeActionRaw(requestParameters: InvokeBridgeActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeActionResponse>> {
        const requestOptions = await this.invokeBridgeActionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async invokeBridgeAction(requestParameters: InvokeBridgeActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeActionResponse> {
        const response = await this.invokeBridgeActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBridgeDefinitions without sending the request
     */
    async listBridgeDefinitionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/bridge/definitions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listBridgeDefinitionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeDefinitionListResponse>> {
        const requestOptions = await this.listBridgeDefinitionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async listBridgeDefinitions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeDefinitionListResponse> {
        const response = await this.listBridgeDefinitionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBridgeRuns without sending the request
     */
    async listBridgeRunsRequestOpts(requestParameters: ListBridgeRunsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/bridge/runs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listBridgeRunsRaw(requestParameters: ListBridgeRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeRunListResponse>> {
        const requestOptions = await this.listBridgeRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async listBridgeRuns(requestParameters: ListBridgeRunsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeRunListResponse> {
        const response = await this.listBridgeRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for previewBridgeFile without sending the request
     */
    async previewBridgeFileRequestOpts(requestParameters: PreviewBridgeFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['definitionId'] == null) {
            throw new runtime.RequiredError(
                'definitionId',
                'Required parameter "definitionId" was null or undefined when calling previewBridgeFile().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling previewBridgeFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['context'] != null) {
            formParams.append('context', requestParameters['context'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['headerRow'] != null) {
            formParams.append('headerRow', requestParameters['headerRow'] as any);
        }

        if (requestParameters['idempotencyKey'] != null) {
            formParams.append('idempotencyKey', requestParameters['idempotencyKey'] as any);
        }

        if (requestParameters['mappingMode'] != null) {
            formParams.append('mappingMode', requestParameters['mappingMode'] as any);
        }

        if (requestParameters['mappingProposal'] != null) {
            formParams.append('mappingProposal', requestParameters['mappingProposal'] as any);
        }

        if (requestParameters['sheetName'] != null) {
            formParams.append('sheetName', requestParameters['sheetName'] as any);
        }

        if (requestParameters['targetSchema'] != null) {
            formParams.append('targetSchema', requestParameters['targetSchema'] as any);
        }


        let urlPath = `/v1/bridge/definitions/{definition_id}/runs/preview-file`;
        urlPath = urlPath.replace(`{${"definition_id"}}`, encodeURIComponent(String(requestParameters['definitionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async previewBridgeFileRaw(requestParameters: PreviewBridgeFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeRunResponse>> {
        const requestOptions = await this.previewBridgeFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async previewBridgeFile(requestParameters: PreviewBridgeFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeRunResponse> {
        const response = await this.previewBridgeFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for previewBridgeRun without sending the request
     */
    async previewBridgeRunRequestOpts(requestParameters: PreviewBridgeRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['definitionId'] == null) {
            throw new runtime.RequiredError(
                'definitionId',
                'Required parameter "definitionId" was null or undefined when calling previewBridgeRun().'
            );
        }

        if (requestParameters['bridgeRunPreviewRequest'] == null) {
            throw new runtime.RequiredError(
                'bridgeRunPreviewRequest',
                'Required parameter "bridgeRunPreviewRequest" was null or undefined when calling previewBridgeRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/bridge/definitions/{definition_id}/runs/preview`;
        urlPath = urlPath.replace(`{${"definition_id"}}`, encodeURIComponent(String(requestParameters['definitionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['bridgeRunPreviewRequest'],
        };
    }

    /**
     */
    async previewBridgeRunRaw(requestParameters: PreviewBridgeRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BridgeRunResponse>> {
        const requestOptions = await this.previewBridgeRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async previewBridgeRun(requestParameters: PreviewBridgeRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BridgeRunResponse> {
        const response = await this.previewBridgeRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
